const WORD_PAIRS = [
  { civilian: 'Chat', undercover: 'Tigre' },
  { civilian: 'Pizza', undercover: 'Lasagne' },
  { civilian: 'Plage', undercover: 'Piscine' },
  { civilian: 'Avion', undercover: 'Helicoptere' },
  { civilian: 'Laptop', undercover: 'Tablette' },
  { civilian: 'Cafe', undercover: 'The' },
  { civilian: 'Football', undercover: 'Rugby' },
  { civilian: 'Neige', undercover: 'Glace' },
  { civilian: 'Lune', undercover: 'Soleil' },
  { civilian: 'Banane', undercover: 'Mangue' },
  { civilian: 'Ocean', undercover: 'Riviere' },
  { civilian: 'Moto', undercover: 'Velo' },
  { civilian: 'Cinema', undercover: 'Theatre' },
  { civilian: 'Paris', undercover: 'Rome' },
  { civilian: 'Boulanger', undercover: 'Patisserie' },
  { civilian: 'Batterie', undercover: 'Guitare' },
  { civilian: 'Docteur', undercover: 'Infirmier' },
  { civilian: 'Chocolat', undercover: 'Vanille' },
  { civilian: 'Montagne', undercover: 'Colline' },
  { civilian: 'Taxi', undercover: 'Bus' },

  // Lieux (faciles)
  { civilian: 'Ecole', undercover: 'College' },
  { civilian: 'Hopital', undercover: 'Clinique' },
  { civilian: 'Supermarche', undercover: 'Epicerie' },
  { civilian: 'Aeroport', undercover: 'Gare' },
  { civilian: 'Bibliotheque', undercover: 'Librairie' },
  { civilian: 'Stade', undercover: 'Gymnase' },
  { civilian: 'Restaurant', undercover: 'Fastfood' },
  { civilian: 'Hotel', undercover: 'Auberge' },
  { civilian: 'Musee', undercover: 'Galerie' },
  { civilian: 'Parc', undercover: 'Jardin' },
  { civilian: 'Foret', undercover: 'Jungle' },
  { civilian: 'Ville', undercover: 'Village' },
  { civilian: 'Metropole', undercover: 'Capitale' },
  { civilian: 'Ile', undercover: 'Peninsule' },
  { civilian: 'Desert', undercover: 'Savane' },
  { civilian: 'Pont', undercover: 'Tunnel' },
  { civilian: 'Port', undercover: 'Marina' },
  { civilian: 'Chateau', undercover: 'Palais' },
  { civilian: 'Temple', undercover: 'Sanctuaire' },
  { civilian: 'Marche', undercover: 'Bazar' },

  // Anime (faciles)
  { civilian: 'Naruto (Perso Anime)', undercover: 'Sasuke (Perso Anime)' },
  { civilian: 'Luffy (Perso Anime)', undercover: 'Zoro (Perso Anime)' },
  { civilian: 'Goku (Perso Anime)', undercover: 'Vegeta (Perso Anime)' },
  { civilian: 'Pikachu (Perso Anime)', undercover: 'Evoli (Perso Anime)' },
  { civilian: 'Saitama (Perso Anime)', undercover: 'Genos (Perso Anime)' },
  { civilian: 'Tanjiro (Perso Anime)', undercover: 'Zenitsu (Perso Anime)' },
  { civilian: 'Nezuko (Perso Anime)', undercover: 'Shinobu (Perso Anime)' },
  { civilian: 'Nami (Perso Anime)', undercover: 'Robin (Perso Anime)' },
  { civilian: 'Mikasa (Perso Anime)', undercover: 'Levi (Perso Anime)' },
  { civilian: 'Eren (Perso Anime)', undercover: 'Armin (Perso Anime)' },
  { civilian: 'Itachi (Perso Anime)', undercover: 'Kakashi (Perso Anime)' },
  { civilian: 'Hinata (Perso Anime)', undercover: 'Sakura (Perso Anime)' },
  { civilian: 'Jiraiya (Perso Anime)', undercover: 'Orochimaru (Perso Anime)' },
  { civilian: 'All Might (Perso Anime)', undercover: 'Deku (Perso Anime)' },
  { civilian: 'Bakugo (Perso Anime)', undercover: 'Todoroki (Perso Anime)' },
  { civilian: 'Gojo (Perso Anime)', undercover: 'Sukuna (Perso Anime)' },
  { civilian: 'Yuji (Perso Anime)', undercover: 'Megumi (Perso Anime)' },
  { civilian: 'Ichigo (Perso Anime)', undercover: 'Rukia (Perso Anime)' },
  { civilian: 'Light (Perso Anime)', undercover: 'L (Perso Anime)' },
  { civilian: 'Natsu (Perso Anime)', undercover: 'Gray (Perso Anime)' },
  { civilian: 'Gon (Perso Anime)', undercover: 'Killua (Perso Anime)' },
  { civilian: 'Hisoka (Perso Anime)', undercover: 'Kurapika (Perso Anime)' },
  { civilian: 'Edward (Perso Anime)', undercover: 'Alphonse (Perso Anime)' },
  { civilian: 'Lelouch (Perso Anime)', undercover: 'Suzaku (Perso Anime)' },
  { civilian: 'Inuyasha (Perso Anime)', undercover: 'Kagome (Perso Anime)' },
  { civilian: 'Rem (Perso Anime)', undercover: 'Emilia (Perso Anime)' },
  { civilian: 'Subaru (Perso Anime)', undercover: 'Otto (Perso Anime)' },
  { civilian: 'Sanji (Perso Anime)', undercover: 'Usopp (Perso Anime)' },
  { civilian: 'Chopper (Perso Anime)', undercover: 'Brook (Perso Anime)' },
  { civilian: 'Franky (Perso Anime)', undercover: 'Jinbe (Perso Anime)' },
  { civilian: 'Ace (Perso Anime)', undercover: 'Sabo (Perso Anime)' },
  { civilian: 'Shanks (Perso Anime)', undercover: 'Mihawk (Perso Anime)' },
  { civilian: 'Law (Perso Anime)', undercover: 'Kid (Perso Anime)' },
  { civilian: 'Yamato (Perso Anime)', undercover: 'Carrot (Perso Anime)' },
  { civilian: 'Gaara (Perso Anime)', undercover: 'Neji (Perso Anime)' },
  { civilian: 'Rock Lee (Perso Anime)', undercover: 'Shikamaru (Perso Anime)' },
  { civilian: 'Tsunade (Perso Anime)', undercover: 'Sakura (Perso Anime)' },
  { civilian: 'Madara (Perso Anime)', undercover: 'Obito (Perso Anime)' },
  { civilian: 'Pain (Perso Anime)', undercover: 'Konan (Perso Anime)' },
  { civilian: 'Minato (Perso Anime)', undercover: 'Kakashi (Perso Anime)' },
  { civilian: 'Hashirama (Perso Anime)', undercover: 'Tobirama (Perso Anime)' },
  { civilian: 'Boruto (Perso Anime)', undercover: 'Sarada (Perso Anime)' },
  { civilian: 'Kawaki (Perso Anime)', undercover: 'Mitsuki (Perso Anime)' },
  { civilian: 'Rengoku (Perso Anime)', undercover: 'Tengen (Perso Anime)' },
  { civilian: 'Muichiro (Perso Anime)', undercover: 'Mitsuri (Perso Anime)' },
  { civilian: 'Inosuke (Perso Anime)', undercover: 'Zenitsu (Perso Anime)' },
  { civilian: 'Asta (Perso Anime)', undercover: 'Yuno (Perso Anime)' },
  { civilian: 'Noelle (Perso Anime)', undercover: 'Mimosa (Perso Anime)' },
  { civilian: 'Eren (Perso Anime)', undercover: 'Reiner (Perso Anime)' },
  { civilian: 'Annie (Perso Anime)', undercover: 'Pieck (Perso Anime)' },
  { civilian: 'Erwin (Perso Anime)', undercover: 'Hange (Perso Anime)' },
  { civilian: 'Kira (Perso Anime)', undercover: 'Ryuk (Perso Anime)' },
  { civilian: 'Near (Perso Anime)', undercover: 'Mello (Perso Anime)' },
  { civilian: 'Yagami (Perso Anime)', undercover: 'L (Perso Anime)' },
  { civilian: 'Gintoki (Perso Anime)', undercover: 'Kagura (Perso Anime)' },
  { civilian: 'Mob (Perso Anime)', undercover: 'Reigen (Perso Anime)' },
  { civilian: 'Koro Sensei (Perso Anime)', undercover: 'Nagisa (Perso Anime)' },
  { civilian: 'Jotaro (Perso Anime)', undercover: 'Dio (Perso Anime)' },
  { civilian: 'Josuke (Perso Anime)', undercover: 'Giorno (Perso Anime)' },
  { civilian: 'Denji (Perso Anime)', undercover: 'Power (Perso Anime)' },
  { civilian: 'Makima (Perso Anime)', undercover: 'Aki (Perso Anime)' },
  { civilian: 'Maomao (Perso Anime)', undercover: 'Jinshi (Perso Anime)' },
  { civilian: 'Gojo (Perso Anime)', undercover: 'Geto (Perso Anime)' },
  { civilian: 'Toji (Perso Anime)', undercover: 'Sukuna (Perso Anime)' },
  { civilian: 'Nanami (Perso Anime)', undercover: 'Todo (Perso Anime)' },
  { civilian: 'Yuta (Perso Anime)', undercover: 'Maki (Perso Anime)' },
  { civilian: 'Kakashi (Perso Anime)', undercover: 'Gai (Perso Anime)' },
  { civilian: 'Obito (Perso Anime)', undercover: 'Madara (Perso Anime)' },
  { civilian: 'Minato (Perso Anime)', undercover: 'Tobirama (Perso Anime)' },
  { civilian: 'Itadori (Perso Anime)', undercover: 'Megumi (Perso Anime)' },
  { civilian: 'Rimuru (Perso Anime)', undercover: 'Diablo (Perso Anime)' },
  { civilian: 'Anya (Perso Anime)', undercover: 'Loid (Perso Anime)' },
  { civilian: 'Yor (Perso Anime)', undercover: 'Fiona (Perso Anime)' },
  { civilian: 'Aizen (Perso Anime)', undercover: 'Urahara (Perso Anime)' },
  { civilian: 'Byakuya (Perso Anime)', undercover: 'Kenpachi (Perso Anime)' },
  { civilian: 'Giyu (Perso Anime)', undercover: 'Rengoku (Perso Anime)' },
  { civilian: 'Tengen (Perso Anime)', undercover: 'Muichiro (Perso Anime)' },
  { civilian: 'Mitsuri (Perso Anime)', undercover: 'Shinobu (Perso Anime)' },
  { civilian: 'Dabi (Perso Anime)', undercover: 'Shigaraki (Perso Anime)' },
  { civilian: 'All For One (Perso Anime)', undercover: 'Endeavor (Perso Anime)' },
  { civilian: 'Sasori (Perso Anime)', undercover: 'Deidara (Perso Anime)' },
  { civilian: 'Kisame (Perso Anime)', undercover: 'Itachi (Perso Anime)' },
  { civilian: 'Kaguya (Perso Anime)', undercover: 'Madara (Perso Anime)' },

  // Titres d anime (categorie dediee)
  { civilian: 'Naruto (Anime)', undercover: 'One Piece (Anime)' },
  { civilian: 'Bleach (Anime)', undercover: 'Fairy Tail (Anime)' },
  { civilian: 'Dragon Ball (Anime)', undercover: 'One Punch Man (Anime)' },
  { civilian: 'Demon Slayer (Anime)', undercover: 'Jujutsu Kaisen (Anime)' },
  { civilian: 'Attack On Titan (Anime)', undercover: 'Death Note (Anime)' },
  { civilian: 'My Hero Academia (Anime)', undercover: 'Black Clover (Anime)' },
  { civilian: 'Chainsaw Man (Anime)', undercover: 'Tokyo Ghoul (Anime)' },
  { civilian: 'Hunter XHunter (Anime)', undercover: 'Yu Yu Hakusho (Anime)' },
  { civilian: 'Code Geass (Anime)', undercover: 'Steins Gate (Anime)' },
  { civilian: 'Spy XFamily (Anime)', undercover: 'Kaguya Sama (Anime)' },
  { civilian: 'Haikyu (Anime)', undercover: 'Kuroko No Basket (Anime)' },
  { civilian: 'Blue Lock (Anime)', undercover: 'Captain Tsubasa (Anime)' },
  { civilian: 'Pokemon (Anime)', undercover: 'Digimon (Anime)' },
  { civilian: 'Jo Jo (Anime)', undercover: 'Baki (Anime)' },
  { civilian: 'Vinland Saga (Anime)', undercover: 'Dr Stone (Anime)' },
  { civilian: 'Solo Leveling (Anime)', undercover: 'Tower Of God (Anime)' },
  { civilian: 'Blue Exorcist (Anime)', undercover: 'Noragami (Anime)' },
  { civilian: 'Fire Force (Anime)', undercover: 'Soul Eater (Anime)' },
  { civilian: 'Mob Psycho (Anime)', undercover: 'One Punch Man (Anime)' },
  { civilian: 'Tokyo Revengers (Anime)', undercover: 'Wind Breaker (Anime)' },
  { civilian: 'Monster (Anime)', undercover: 'Psycho Pass (Anime)' },
  { civilian: 'Black Lagoon (Anime)', undercover: 'Jormungand (Anime)' },
  { civilian: 'Parasyte (Anime)', undercover: 'Ajin (Anime)' },
  { civilian: 'Re Zero (Anime)', undercover: 'Konosuba (Anime)' },
  { civilian: 'Classroom Of The Elite (Anime)', undercover: 'Tomodachi Game (Anime)' },
  { civilian: 'Code Geass (Anime)', undercover: 'Guilty Crown (Anime)' },
  { civilian: 'Hellsing (Anime)', undercover: 'Castlevania (Anime)' },
  { civilian: 'Mushoku Tensei (Anime)', undercover: 'That Time I Got Reincarnated As A Slime (Anime)' },
  { civilian: 'Overlord (Anime)', undercover: 'Log Horizon (Anime)' },
  { civilian: 'Initial D (Anime)', undercover: 'MF Ghost (Anime)' },

  // Lieux d anime (One Piece, Naruto, etc.)
  { civilian: 'Wano', undercover: 'Dressrosa' },
  { civilian: 'Enies Lobby', undercover: 'Marineford' },
  { civilian: 'Whole Cake', undercover: 'Wano' },
  { civilian: 'Skypiea', undercover: 'Alabasta' },
  { civilian: 'Water 7', undercover: 'Enies Lobby' },
  { civilian: 'Punk Hazard', undercover: 'Dressrosa' },
  { civilian: 'Sabaody', undercover: 'Amazon Lily' },
  { civilian: 'Impel Down', undercover: 'Marineford' },
  { civilian: 'Laugh Tale', undercover: 'Raftel' },
  { civilian: 'Loguetown', undercover: 'Shells Town' },
  { civilian: 'Onigashima', undercover: 'Wano' },
  { civilian: 'Zou', undercover: 'Wano' },
  { civilian: 'Jaya', undercover: 'Skypiea' },
  { civilian: 'Konoha', undercover: 'Suna' },
  { civilian: 'Kiri', undercover: 'Kumo' },
  { civilian: 'Iwa', undercover: 'Ame' },
  { civilian: 'Udon (Wano)', undercover: 'Onigashima' },
  { civilian: 'Egghead', undercover: 'Punk Hazard' },
  { civilian: 'Elbaf', undercover: 'Wano' },
  { civilian: 'Hueco Mundo', undercover: 'Soul Society' },
  { civilian: 'Las Noches', undercover: 'Karakura' },
  { civilian: 'Shibuya', undercover: 'Shinjuku' },
  { civilian: 'District Rouge', undercover: 'Mugen Train' },
  { civilian: 'Paradis', undercover: 'Marley' },
  { civilian: 'Wall Maria', undercover: 'Wall Rose' },
  { civilian: 'UA (Lieu Anime)', undercover: 'Shiketsu (Lieu Anime)' },
  { civilian: 'Kamino (Lieu Anime)', undercover: 'Hosu (Lieu Anime)' },
  { civilian: 'Aincrad', undercover: 'Alfheim' },

  // Techniques anime
  { civilian: 'Rasengan (Technique Anime)', undercover: 'Chidori (Technique Anime)' },
  { civilian: 'Kamehameha (Technique Anime)', undercover: 'Final Flash (Technique Anime)' },
  { civilian: 'Bankai (Technique Anime)', undercover: 'Shikai (Technique Anime)' },
  { civilian: 'Domain Expansion (Technique Anime)', undercover: 'Cursed Technique (Technique Anime)' },
  { civilian: 'Haki Observation (Technique Anime)', undercover: 'Haki Armement (Technique Anime)' },
  { civilian: 'Gear 4 (Technique Anime)', undercover: 'Gear 5 (Technique Anime)' },
  { civilian: 'Souffle Eau (Technique Anime)', undercover: 'Souffle Feu (Technique Anime)' },
  { civilian: 'Sharingan (Technique Anime)', undercover: 'Byakugan (Technique Anime)' },
  { civilian: 'Mangekyo (Technique Anime)', undercover: 'Rinnegan (Technique Anime)' },
  { civilian: 'Kaioken (Technique Anime)', undercover: 'Ultra Instinct (Technique Anime)' },
  { civilian: 'One For All (Technique Anime)', undercover: 'All For One (Technique Anime)' },
  { civilian: 'Black Flash (Technique Anime)', undercover: 'Purple (Technique Anime)' },
  { civilian: 'Getsuga Tensho (Technique Anime)', undercover: 'Cero (Technique Anime)' },
  { civilian: 'Susanoo (Technique Anime)', undercover: 'Amaterasu (Technique Anime)' },
  { civilian: 'Multi Clonage (Technique Anime)', undercover: 'Substitution (Technique Anime)' },

  // Films connus
  { civilian: 'Titanic', undercover: 'Avatar' },
  { civilian: 'Avatar', undercover: 'Avengers' },
  { civilian: 'Interstellar', undercover: 'Inception' },
  { civilian: 'Inception', undercover: 'Tenet' },
  { civilian: 'Joker', undercover: 'Batman' },
  { civilian: 'Batman', undercover: 'Superman' },
  { civilian: 'Spider Man', undercover: 'Iron Man' },
  { civilian: 'Thor', undercover: 'Loki' },
  { civilian: 'Black Panther', undercover: 'Doctor Strange' },
  { civilian: 'Matrix', undercover: 'John Wick' },
  { civilian: 'Gladiator', undercover: 'Troie' },
  { civilian: 'Harry Potter', undercover: 'Le Seigneur Des Anneaux' },
  { civilian: 'Star Wars', undercover: 'Star Trek' },
  { civilian: 'Fast And Furious', undercover: 'Transformers' },
  { civilian: 'Mission Impossible', undercover: 'James Bond' },
  { civilian: 'Le Roi Lion', undercover: 'Aladdin' },
  { civilian: 'Toy Story', undercover: 'Cars' },
  { civilian: 'Shrek', undercover: 'Kung Fu Panda' },
  { civilian: 'Frozen', undercover: 'Raiponce' },
  { civilian: 'Scream', undercover: 'Conjuring' },

  // Personnages connus de films
  { civilian: 'Harry Potter (Perso Film)', undercover: 'Hermione (Perso Film)' },
  { civilian: 'Ron Weasley (Perso Film)', undercover: 'Draco Malfoy (Perso Film)' },
  { civilian: 'Voldemort (Perso Film)', undercover: 'Dumbledore (Perso Film)' },
  { civilian: 'Frodon (Perso Film)', undercover: 'Sam (Perso Film)' },
  { civilian: 'Aragorn (Perso Film)', undercover: 'Legolas (Perso Film)' },
  { civilian: 'Gandalf (Perso Film)', undercover: 'Saroumane (Perso Film)' },
  { civilian: 'Luke Skywalker (Perso Film)', undercover: 'Han Solo (Perso Film)' },
  { civilian: 'Dark Vador (Perso Film)', undercover: 'Obi Wan (Perso Film)' },
  { civilian: 'Leia (Perso Film)', undercover: 'Padme (Perso Film)' },
  { civilian: 'Tony Stark (Perso Film)', undercover: 'Steve Rogers (Perso Film)' },
  { civilian: 'Thor (Perso Film)', undercover: 'Loki (Perso Film)' },
  { civilian: 'Thanos (Perso Film)', undercover: 'Ultron (Perso Film)' },
  { civilian: 'Peter Parker (Perso Film)', undercover: 'Miles Morales (Perso Film)' },
  { civilian: 'Bruce Wayne (Perso Film)', undercover: 'Clark Kent (Perso Film)' },
  { civilian: 'Joker (Perso Film)', undercover: 'Harley Quinn (Perso Film)' },
  { civilian: 'Neo (Perso Film)', undercover: 'Morpheus (Perso Film)' },
  { civilian: 'John Wick (Perso Film)', undercover: 'Jason Bourne (Perso Film)' },
  { civilian: 'Jack Sparrow (Perso Film)', undercover: 'Will Turner (Perso Film)' },
  { civilian: 'Indiana Jones (Perso Film)', undercover: 'Lara Croft (Perso Film)' },
  { civilian: 'Maximus (Perso Film)', undercover: 'Achille (Perso Film)' },
  { civilian: 'Elsa (Perso Film)', undercover: 'Anna (Perso Film)' },
  { civilian: 'Simba (Perso Film)', undercover: 'Mufasa (Perso Film)' },
  { civilian: 'Shrek (Perso Film)', undercover: 'Fiona (Perso Film)' },
  { civilian: 'Po (Perso Film)', undercover: 'Shifu (Perso Film)' },
  { civilian: 'Woody (Perso Film)', undercover: 'Buzz (Perso Film)' },
  { civilian: 'Lightning Mc Queen (Perso Film)', undercover: 'Martin (Perso Film)' },
  { civilian: 'Katniss (Perso Film)', undercover: 'Peeta (Perso Film)' },
  { civilian: 'Deadpool (Perso Film)', undercover: 'Wolverine (Perso Film)' },
  { civilian: 'Rambo (Perso Film)', undercover: 'Rocky (Perso Film)' },
  { civilian: 'Forrest Gump (Perso Film)', undercover: 'Benjamin Button (Perso Film)' },


  // Jeux video / personnages connus
  { civilian: 'Mario', undercover: 'Luigi' },
  { civilian: 'Peach', undercover: 'Daisy' },
  { civilian: 'Bowser', undercover: 'Wario' },
  { civilian: 'Zelda', undercover: 'Link' },
  { civilian: 'Ganondorf', undercover: 'Zelda' },
  { civilian: 'Kirby', undercover: 'Meta Knight' },
  { civilian: 'Sonic', undercover: 'Shadow' },
  { civilian: 'Tails', undercover: 'Knuckles' },
  { civilian: 'Pikachu', undercover: 'Charizard' },
  { civilian: 'Mewtwo', undercover: 'Lucario' },
  { civilian: 'Steve', undercover: 'Creeper' },
  { civilian: 'Herobrine', undercover: 'Enderman' },
  { civilian: 'Fortnite', undercover: 'Apex' },
  { civilian: 'Valorant', undercover: 'CS 2' },
  { civilian: 'League Of Legends', undercover: 'Dota 2' },
  { civilian: 'Overwatch', undercover: 'Paladins' },
  { civilian: 'Call Of Duty', undercover: 'Battlefield' },
  { civilian: 'GTA', undercover: 'Watch Dogs' },
  { civilian: 'Red Dead', undercover: 'GTA' },
  { civilian: 'Kratos', undercover: 'Atreus' },
  { civilian: 'Master Chief', undercover: 'Doomguy' },
  { civilian: 'Lara Croft', undercover: 'Nathan Drake' },
  { civilian: 'Geralt', undercover: 'Ciri' },
  { civilian: 'Arthur Morgan', undercover: 'John Marston' },
  { civilian: 'Ezio', undercover: 'Altair' },
  { civilian: 'Pac Man', undercover: 'Bomberman' },
  { civilian: 'Among Us', undercover: 'Fall Guys' },
  { civilian: 'Brawl Stars', undercover: 'Clash Royale' },
  { civilian: 'Clash Of Clans', undercover: 'Boom Beach' },
  { civilian: 'FIFA', undercover: 'e Football' },
  { civilian: 'Rocket League', undercover: 'Trackmania' },
  { civilian: 'Roblox', undercover: 'Minecraft' },

  // Series / persos de series tres connus
  { civilian: 'Walter White (Perso Série)', undercover: 'Jesse Pinkman (Perso Série)' },
  { civilian: 'Saul Goodman (Perso Série)', undercover: 'Gus Fring (Perso Série)' },
  { civilian: 'Jon Snow (Perso Série)', undercover: 'Daenerys (Perso Série)' },
  { civilian: 'Tyrion (Perso Série)', undercover: 'Arya (Perso Série)' },
  { civilian: 'Eleven (Perso Série)', undercover: 'Mike (Perso Série)' },
  { civilian: 'Dustin (Perso Série)', undercover: 'Will (Perso Série)' },
  { civilian: 'Sherlock (Perso Série)', undercover: 'Watson (Perso Série)' },
  { civilian: 'Michael Scott (Perso Série)', undercover: 'Dwight (Perso Série)' },
  { civilian: 'Ross (Perso Série)', undercover: 'Chandler (Perso Série)' },
  { civilian: 'Monica (Perso Série)', undercover: 'Rachel (Perso Série)' },
  { civilian: 'Barney (Perso Série)', undercover: 'Ted (Perso Série)' },
  { civilian: 'House (Perso Série)', undercover: 'Wilson (Perso Série)' },
  { civilian: 'Rick (Perso Série)', undercover: 'Daryl (Perso Série)' },
  { civilian: 'Meredith (Perso Série)', undercover: 'Cristina (Perso Série)' },
  { civilian: 'Tokyo (Perso Série)', undercover: 'Nairobi (Perso Série)' },
  { civilian: 'Professor (Perso Série)', undercover: 'Berlin (Perso Série)' },
  { civilian: 'Homelander (Perso Série)', undercover: 'Butcher (Perso Série)' },
  { civilian: 'Loki (Perso Série)', undercover: 'Sylvie (Perso Série)' },
  { civilian: 'Wednesday (Perso Série)', undercover: 'Enid (Perso Série)' },
  { civilian: 'Lucifer (Perso Série)', undercover: 'Chloe (Perso Série)' },

  // Villes et lieux (supplementaires)
  { civilian: 'Paris (Ville)', undercover: 'Lyon (Ville)' },
  { civilian: 'Marseille (Ville)', undercover: 'Nice (Ville)' },
  { civilian: 'Toulouse (Ville)', undercover: 'Bordeaux (Ville)' },
  { civilian: 'Lille (Ville)', undercover: 'Nantes (Ville)' },
  { civilian: 'Strasbourg (Ville)', undercover: 'Metz (Ville)' },
  { civilian: 'Bruxelles (Ville)', undercover: 'Amsterdam (Ville)' },
  { civilian: 'Madrid (Ville)', undercover: 'Barcelone (Ville)' },
  { civilian: 'Lisbonne (Ville)', undercover: 'Porto (Ville)' },
  { civilian: 'Londres (Ville)', undercover: 'Manchester (Ville)' },
  { civilian: 'Dublin (Ville)', undercover: 'Belfast (Ville)' },
  { civilian: 'Rome (Ville)', undercover: 'Milan (Ville)' },
  { civilian: 'Naples (Ville)', undercover: 'Florence (Ville)' },
  { civilian: 'Berlin (Ville)', undercover: 'Munich (Ville)' },
  { civilian: 'Vienne (Ville)', undercover: 'Prague (Ville)' },
  { civilian: 'Budapest (Ville)', undercover: 'Varsovie (Ville)' },
  { civilian: 'Athenes (Ville)', undercover: 'Istanbul (Ville)' },
  { civilian: 'New York (Ville)', undercover: 'Chicago (Ville)' },
  { civilian: 'Los Angeles (Ville)', undercover: 'San Francisco (Ville)' },
  { civilian: 'Toronto (Ville)', undercover: 'Montreal (Ville)' },
  { civilian: 'Mexico (Ville)', undercover: 'Bogota (Ville)' },
  { civilian: 'Rio (Ville)', undercover: 'Sao Paulo (Ville)' },
  { civilian: 'Buenos Aires (Ville)', undercover: 'Santiago (Ville)' },
  { civilian: 'Le Caire (Ville)', undercover: 'Casablanca (Ville)' },
  { civilian: 'Dubai (Ville)', undercover: 'Doha (Ville)' },
  { civilian: 'Tokyo (Ville)', undercover: 'Osaka (Ville)' },
  { civilian: 'Seoul (Ville)', undercover: 'Busan (Ville)' },
  { civilian: 'Pekin (Ville)', undercover: 'Shanghai (Ville)' },
  { civilian: 'Hong Kong (Ville)', undercover: 'Taipei (Ville)' },
  { civilian: 'Bangkok (Ville)', undercover: 'Singapour (Ville)' },
  { civilian: 'Sydney (Ville)', undercover: 'Melbourne (Ville)' },

  { civilian: 'École', undercover: 'Université' },
  { civilian: 'Hôpital', undercover: 'Clinique' },
  { civilian: 'Pharmacie', undercover: 'Laboratoire' },
  { civilian: 'Boulangerie', undercover: 'Pâtisserie' },
  { civilian: 'Supermarché', undercover: 'Hypermarché' },
  { civilian: 'Bibliothèque', undercover: 'Médiathèque' },
  { civilian: 'Mairie', undercover: 'Préfecture' },
  { civilian: 'Commissariat', undercover: 'Gendarmerie' },
  { civilian: 'Caserne', undercover: 'Base militaire' },
  { civilian: 'Stade', undercover: 'Gymnase' },
  { civilian: 'Piscine', undercover: 'Patinoire' },
  { civilian: 'Cinéma', undercover: 'Théâtre' },
  { civilian: 'Musée', undercover: 'Galerie' },
  { civilian: 'Parc', undercover: 'Jardin' },
  { civilian: 'Forêt', undercover: 'Bois' },
  { civilian: 'Montagne', undercover: 'Colline' },
  { civilian: 'Plage', undercover: 'Crique' },
  { civilian: 'Lac', undercover: 'Étang' },
  { civilian: 'Rivière', undercover: 'Fleuve' },
  { civilian: 'Port', undercover: 'Marina' },
  { civilian: 'Aéroport', undercover: 'Gare' },
  { civilian: 'Station métro', undercover: 'Arrêt de bus' },
  { civilian: 'Hôtel', undercover: 'Auberge' },
  { civilian: 'Camping', undercover: 'Village vacances' },
  { civilian: 'Château', undercover: 'Palais' },
  { civilian: 'Temple', undercover: 'Église' },
  { civilian: 'Mosquée', undercover: 'Cathédrale' },
  { civilian: 'Marché', undercover: 'Centre commercial' },
  { civilian: 'Pont', undercover: 'Tunnel' },
  { civilian: 'Île', undercover: 'Péninsule' },
  { civilian: 'Stylo', undercover: 'Crayon' },
  { civilian: 'Gomme', undercover: 'Taille Crayon' },
  { civilian: 'Cahier', undercover: 'Agenda' },
  { civilian: 'Sac ADos', undercover: 'Valise' },
  { civilian: 'Bouteille', undercover: 'Gourde' },
  { civilian: 'Verre', undercover: 'Tasse' },
  { civilian: 'Assiette', undercover: 'Bol' },
  { civilian: 'Cuillere', undercover: 'Fourchette' },
  { civilian: 'Couteau', undercover: 'Econome' },
  { civilian: 'Poele', undercover: 'Casserole' },
  { civilian: 'Mixer', undercover: 'Blender' },
  { civilian: 'Lampe', undercover: 'Ampoule' },
  { civilian: 'Chargeur', undercover: 'Cable USB' },
  { civilian: 'Ecouteurs', undercover: 'Casque' },
  { civilian: 'Clavier', undercover: 'Souris' },
  { civilian: 'Telecommande', undercover: 'Manette' },
  { civilian: 'Horloge', undercover: 'Montre' },
  { civilian: 'Parapluie', undercover: 'Kway' },
  { civilian: 'Cle', undercover: 'Serrure' },
  { civilian: 'Pinceau', undercover: 'Rouleau' },

  // Metiers (proches)
  { civilian: 'Pompier', undercover: 'Policier' },
  { civilian: 'Boulanger', undercover: 'Patissier' },
  { civilian: 'Professeur', undercover: 'Instituteur' },
  { civilian: 'Medecin', undercover: 'Chirurgien' },
  { civilian: 'Infirmier', undercover: 'Aide Soignant' },
  { civilian: 'Veterinaire', undercover: 'Toiletteur' },
  { civilian: 'Pilote', undercover: 'Steward' },
  { civilian: 'Chauffeur', undercover: 'Livreur' },
  { civilian: 'Cuisinier', undercover: 'Chef' },
  { civilian: 'Serveur', undercover: 'Barman' },
  { civilian: 'Architecte', undercover: 'Ingenieur' },
  { civilian: 'Macon', undercover: 'Plombier' },
  { civilian: 'Electricien', undercover: 'Technicien' },
  { civilian: 'Journaliste', undercover: 'Presentateur' },
  { civilian: 'Photographe', undercover: 'Cameraman' },
  { civilian: 'Acteur', undercover: 'Cascadeur' },
  { civilian: 'Chanteur', undercover: 'Rappeur' },
  { civilian: 'Avocat', undercover: 'Juge' },
  { civilian: 'Banquier', undercover: 'Comptable' },
  { civilian: 'Coiffeur', undercover: 'Barbier' },

  // Nourriture
  { civilian: 'Hamburger', undercover: 'Cheeseburger' },
  { civilian: 'Frites', undercover: 'Potatoes' },
  { civilian: 'Riz', undercover: 'Pates' },
  { civilian: 'Poulet', undercover: 'Dinde' },
  { civilian: 'Steak', undercover: 'Escalope' },
  { civilian: 'Saumon', undercover: 'Thon' },
  { civilian: 'Pomme', undercover: 'Poire' },
  { civilian: 'Orange', undercover: 'Mandarine' },
  { civilian: 'Fraise', undercover: 'Framboise' },
  { civilian: 'Biscuit', undercover: 'Gateau' },
  { civilian: 'Glace', undercover: 'Sorbet' },
  { civilian: 'Yaourt', undercover: 'Fromage Blanc' },
  { civilian: 'Lait', undercover: 'Creme' },
  { civilian: 'Eau', undercover: 'Jus' },
  { civilian: 'Soda', undercover: 'Limonade' },

  // Animaux
  { civilian: 'Chien', undercover: 'Loup' },
  { civilian: 'Lion', undercover: 'Leopard' },
  { civilian: 'Cheval', undercover: 'Poney' },
  { civilian: 'Vache', undercover: 'Taureau' },
  { civilian: 'Mouton', undercover: 'Chevre' },
  { civilian: 'Lapin', undercover: 'Lièvre' },
  { civilian: 'Canard', undercover: 'Oie' },
  { civilian: 'Poule', undercover: 'Dinde' },
  { civilian: 'Aigle', undercover: 'Faucon' },
  { civilian: 'Requin', undercover: 'Dauphin' },
  { civilian: 'Baleine', undercover: 'Orque' },
  { civilian: 'Tortue', undercover: 'Crocodile' },
  { civilian: 'Serpent', undercover: 'Iguane' },
  { civilian: 'Abeille', undercover: 'Guêpe' },
  { civilian: 'Papillon', undercover: 'Libellule' },

  // Transports
  { civilian: 'Voiture', undercover: 'Camion' },
  { civilian: 'Scooter', undercover: 'Moto' },
  { civilian: 'Tram', undercover: 'Metro' },
  { civilian: 'Train', undercover: 'TGV' },
  { civilian: 'Bateau', undercover: 'Yacht' },
  { civilian: 'Voilier', undercover: 'Catamaran' },
  { civilian: 'Fusee', undercover: 'Navette' },
  { civilian: 'Drone', undercover: 'Helicoptere' },
  { civilian: 'Skate', undercover: 'Trottinette' },
  { civilian: 'Roller', undercover: 'Skate' },

  // Sports
  { civilian: 'Tennis', undercover: 'Padel' },
  { civilian: 'Basket', undercover: 'Handball' },
  { civilian: 'Volley', undercover: 'Badminton' },
  { civilian: 'Natation', undercover: 'Plongeon' },
  { civilian: 'Boxe', undercover: 'MMA' },
  { civilian: 'Judo', undercover: 'Karate' },
  { civilian: 'Ski', undercover: 'Snowboard' },
  { civilian: 'Surf', undercover: 'Bodyboard' },
  { civilian: 'Cyclisme', undercover: 'VTT' },
  { civilian: 'Athletisme', undercover: 'Triathlon' },

  // Maison / quotidien
  { civilian: 'Canape', undercover: 'Fauteuil' },
  { civilian: 'Lit', undercover: 'Canape Lit' },
  { civilian: 'Oreiller', undercover: 'Coussin' },
  { civilian: 'Couette', undercover: 'Plaid' },
  { civilian: 'Table', undercover: 'Bureau' },
  { civilian: 'Chaise', undercover: 'Tabouret' },
  { civilian: 'Armoire', undercover: 'Commode' },
  { civilian: 'Miroir', undercover: 'Cadre' },
  { civilian: 'Frigo', undercover: 'Congelateur' },
  { civilian: 'Four', undercover: 'Micro Ondes' },
  { civilian: 'Lave Linge', undercover: 'Lave Vaisselle' },
  { civilian: 'Balai', undercover: 'Aspirateur' },
  { civilian: 'Savon', undercover: 'Shampoing' },
  { civilian: 'Dentifrice', undercover: 'Bain De Bouche' },
  { civilian: 'Serviette', undercover: 'Peignoir' },

  // Vetements / accessoires
  { civilian: 'TShirt', undercover: 'Polo' },
  { civilian: 'Chemise', undercover: 'Blouse' },
  { civilian: 'Jean', undercover: 'Pantalon' },
  { civilian: 'Short', undercover: 'Bermuda' },
  { civilian: 'Jupe', undercover: 'Robe' },
  { civilian: 'Veste', undercover: 'Manteau' },
  { civilian: 'Pull', undercover: 'Sweat' },
  { civilian: 'Baskets', undercover: 'Chaussures' },
  { civilian: 'Bonnet', undercover: 'Casquette' },
  { civilian: 'Lunettes', undercover: 'Lentilles' },
  { civilian: 'Sac', undercover: 'Pochette' },
  { civilian: 'Ceinture', undercover: 'Bretelles' },

  // Tech / internet
  { civilian: 'Google', undercover: 'Bing' },
  { civilian: 'You Tube', undercover: 'Twitch' },
  { civilian: 'Instagram', undercover: 'Tik Tok' },
  { civilian: 'Discord', undercover: 'Teamspeak' },
  { civilian: 'Whats App', undercover: 'Telegram' },
  { civilian: 'Netflix', undercover: 'Prime Video' },
  { civilian: 'Spotify', undercover: 'Deezer' },
  { civilian: 'Windows', undercover: 'Linux' },
  { civilian: 'Android', undercover: 'i OS' },
  { civilian: 'Wi Fi', undercover: '4 G' },

  // Musique / instruments
  { civilian: 'Piano', undercover: 'Synthé' },
  { civilian: 'Violon', undercover: 'Alto' },
  { civilian: 'Batterie', undercover: 'Percussion' },
  { civilian: 'Saxophone', undercover: 'Trompette' },
  { civilian: 'Flute', undercover: 'Clarinette' },
  { civilian: 'Concert', undercover: 'Festival' },
  { civilian: 'DJ', undercover: 'Producteur' },
  { civilian: 'Album', undercover: 'Single' },
  { civilian: 'Playlist', undercover: 'Mixtape' },
  { civilian: 'Micro', undercover: 'Casque Studio' },

  // Marques
  { civilian: 'Nike', undercover: 'Adidas' },
  { civilian: 'Puma', undercover: 'Reebok' },
  { civilian: 'Lacoste', undercover: 'Ralph Lauren' },
  { civilian: 'Gucci', undercover: 'Prada' },
  { civilian: 'Zara', undercover: 'H&M' },
  { civilian: 'Apple', undercover: 'Samsung' },
  { civilian: 'Sony', undercover: 'LG' },
  { civilian: 'Coca Cola', undercover: 'Pepsi' },
  { civilian: 'Mc Donalds', undercover: 'Burger King' },
  { civilian: 'KFC', undercover: 'Subway' },
  { civilian: 'New Balance', undercover: 'Asics' },
  { civilian: 'Converse', undercover: 'Vans' },
  { civilian: 'Under Armour', undercover: 'Decathlon' },
  { civilian: 'Levis', undercover: 'Wrangler' },
  { civilian: 'Calvin Klein', undercover: 'Tommy Hilfiger' },
  { civilian: 'Balenciaga', undercover: 'Givenchy' },
  { civilian: 'Louis Vuitton', undercover: 'Dior' },
  { civilian: 'Rolex', undercover: 'Omega' },
  { civilian: 'Tag Heuer', undercover: 'Breitling' },
  { civilian: 'Apple', undercover: 'Google' },
  { civilian: 'Microsoft', undercover: 'Amazon' },
  { civilian: 'Intel', undercover: 'AMD' },
  { civilian: 'Nvidia', undercover: 'Radeon' },
  { civilian: 'Xiaomi', undercover: 'One Plus' },
  { civilian: 'Huawei', undercover: 'Honor' },
  { civilian: 'Oppo', undercover: 'Vivo' },
  { civilian: 'Play Station', undercover: 'Xbox' },
  { civilian: 'Nintendo', undercover: 'Sega' },
  { civilian: 'EA', undercover: 'Ubisoft' },
  { civilian: 'Rockstar', undercover: 'Bethesda' },
  { civilian: 'Netflix', undercover: 'Disney Plus' },
  { civilian: 'Prime Video', undercover: 'Canal Plus' },
  { civilian: 'Spotify', undercover: 'Apple Music' },
  { civilian: 'Deezer', undercover: 'SoundCloud' },
  { civilian: 'Snapchat', undercover: 'Instagram' },
  { civilian: 'Tik Tok', undercover: 'You Tube' },
  { civilian: 'Discord', undercover: 'Slack' },
  { civilian: 'Whats App', undercover: 'Signal' },
  { civilian: 'Telegram', undercover: 'Messenger' },
  { civilian: 'Renault', undercover: 'Peugeot' },
  { civilian: 'Citroen', undercover: 'Volkswagen' },
  { civilian: 'BMW', undercover: 'Mercedes' },
  { civilian: 'Audi', undercover: 'Volvo' },
  { civilian: 'Toyota', undercover: 'Honda' },
  { civilian: 'Nissan', undercover: 'Mazda' },
  { civilian: 'Hyundai', undercover: 'Kia' },
  { civilian: 'Tesla', undercover: 'Polestar' },
  { civilian: 'Ferrari', undercover: 'Lamborghini' },
  { civilian: 'Porsche', undercover: 'Maserati' },
  { civilian: 'Bugatti', undercover: 'McLaren' },
  { civilian: 'Air France', undercover: 'Lufthansa' },
  { civilian: 'Emirates', undercover: 'Qatar Airways' },
  { civilian: 'Ryanair', undercover: 'EasyJet' },
  { civilian: 'Ikea', undercover: 'Conforama' },
  { civilian: 'Leroy Merlin', undercover: 'Castorama' },
  { civilian: 'Carrefour', undercover: 'Auchan' },
  { civilian: 'Leclerc', undercover: 'Intermarche' },
  { civilian: 'Casino', undercover: 'Monoprix' },
  { civilian: 'Aldi', undercover: 'Lidl' },
  { civilian: 'Zara', undercover: 'Uniqlo' },
  { civilian: 'H&M', undercover: 'C&A' },
  { civilian: 'Shein', undercover: 'Temu' },
  { civilian: 'Sephora', undercover: 'Marionnaud' },
  { civilian: 'Nivea', undercover: 'L Oreal' },
  { civilian: 'Maybelline', undercover: 'Revlon' },
  { civilian: 'Coca Cola', undercover: 'Fanta' },
  { civilian: 'Sprite', undercover: '7 Up' },
  { civilian: 'Red Bull', undercover: 'Monster' },
  { civilian: 'Evian', undercover: 'Volvic' },
  { civilian: 'San Pellegrino', undercover: 'Perrier' },
  { civilian: 'Danone', undercover: 'Nestle' },
  { civilian: 'Milka', undercover: 'Lindt' },
  { civilian: 'Kinder', undercover: 'Haribo' },
  { civilian: 'Oreo', undercover: 'LU' },
  { civilian: 'Nutella', undercover: 'Nocciolata' },
  { civilian: 'Mc Donalds', undercover: 'Quick' },
  { civilian: 'Burger King', undercover: 'Five Guys' },
  { civilian: 'Dominos', undercover: 'Pizza Hut' },
  { civilian: 'Starbucks', undercover: 'Costa Coffee' },
  { civilian: 'Nespresso', undercover: 'Senseo' },
  { civilian: 'Samsung', undercover: 'Sony' },
  { civilian: 'Bose', undercover: 'JBL' },
  { civilian: 'Sennheiser', undercover: 'Audio Technica' },

  // Réseaux sociaux
  { civilian: 'Instagram', undercover: 'Tik Tok' },
  { civilian: 'Snapchat', undercover: 'Be Real' },
  { civilian: 'Facebook', undercover: 'X' },
  { civilian: 'You Tube', undercover: 'Twitch' },
  { civilian: 'Whats App', undercover: 'Telegram' },
  { civilian: 'Discord', undercover: 'Messenger' },
  { civilian: 'Linked In', undercover: 'Viadeo' },
  { civilian: 'Reddit', undercover: 'Quora' },

  // Appareils tech
  { civilian: 'i Phone (Appareil)', undercover: 'Samsung Galaxy (Appareil)' },
  { civilian: 'i Pad (Appareil)', undercover: 'Tablette Android (Appareil)' },
  { civilian: 'Mac Book (Appareil)', undercover: 'PCPortable (Appareil)' },
  { civilian: 'Air Pods (Appareil)', undercover: 'Galaxy Buds (Appareil)' },
  { civilian: 'Apple Watch (Appareil)', undercover: 'Montre Connectée (Appareil)' },
  { civilian: 'Play Station 5 (Appareil)', undercover: 'Xbox Series (Appareil)' },
  { civilian: 'Nintendo Switch (Appareil)', undercover: 'Steam Deck (Appareil)' },
  { civilian: 'Alexa (Appareil)', undercover: 'Google Home (Appareil)' },
  { civilian: 'Kindle (Appareil)', undercover: 'Kobo (Appareil)' },

  // Insectes et animaux
  { civilian: 'Fourmi', undercover: 'Termite' },
  { civilian: 'Moustique', undercover: 'Mouche' },
  { civilian: 'Coccinelle', undercover: 'Scarabée' },
  { civilian: 'Criquet', undercover: 'Sauterelle' },
  { civilian: 'Araignée', undercover: 'Scorpion' },
  { civilian: 'Chat', undercover: 'Chien' },
  { civilian: 'Tigre', undercover: 'Lion' },
  { civilian: 'Dauphin', undercover: 'Orque' },
  { civilian: 'Panda', undercover: 'Koala' },
  { civilian: 'Loup', undercover: 'Renard' },

  // Boissons
  { civilian: 'Eau', undercover: 'Eau Gazeuse' },
  { civilian: 'Coca', undercover: 'Pepsi' },
  { civilian: 'Fanta', undercover: 'Orangina' },
  { civilian: 'Ice Tea', undercover: 'Arizona' },
  { civilian: 'Café', undercover: 'Expresso' },
  { civilian: 'Thé', undercover: 'Infusion' },
  { civilian: 'Jus Orange', undercover: 'Jus Pomme' },
  { civilian: 'Limonade', undercover: 'Sprite' },
  { civilian: 'Lait', undercover: 'Lait Amande' },
  { civilian: 'Smoothie', undercover: 'Milkshake' },

  // Fruits et fruits exotiques
  { civilian: 'Pomme', undercover: 'Poire' },
  { civilian: 'Fraise', undercover: 'Framboise' },
  { civilian: 'Cerise', undercover: 'Prune' },
  { civilian: 'Raisin', undercover: 'Myrtille' },
  { civilian: 'Banane', undercover: 'Ananas' },
  { civilian: 'Mangue', undercover: 'Papaye' },
  { civilian: 'Fruit De La Passion', undercover: 'Litchi' },
  { civilian: 'Noix De Coco', undercover: 'Kiwi' },
  { civilian: 'Grenade', undercover: 'Figue' },
  { civilian: 'Pastèque', undercover: 'Melon' },

  // Desserts
  { civilian: 'Tiramisu', undercover: 'Panna Cotta' },
  { civilian: 'Mousse Chocolat', undercover: 'Crème Brûlée' },
  { civilian: 'Éclair', undercover: 'Mille Feuille' },
  { civilian: 'Macaron', undercover: 'Cupcake' },
  { civilian: 'Cheesecake', undercover: 'Brownie' },
  { civilian: 'Gaufre', undercover: 'Crêpe' },
  { civilian: 'Glace Vanille', undercover: 'Sorbet Citron' },
  { civilian: 'Donut', undercover: 'Beignet' },
  { civilian: 'Flan', undercover: 'Clafoutis' },
  { civilian: 'Tarte Pomme', undercover: 'Tarte Citron' },

  // Instruments de musique
  { civilian: 'Guitare', undercover: 'Basse' },
  { civilian: 'Piano', undercover: 'Clavier' },
  { civilian: 'Batterie', undercover: 'Cajon' },
  { civilian: 'Violon', undercover: 'Violoncelle' },
  { civilian: 'Saxophone', undercover: 'Trompette' },
  { civilian: 'Flûte', undercover: 'Clarinette' },
  { civilian: 'Ukulélé', undercover: 'Mandoline' },
  { civilian: 'Harpe', undercover: 'Lyre' },
  { civilian: 'Accordéon', undercover: 'Harmonica' },
  { civilian: 'Djembé', undercover: 'Bongo' },

  // Mythologie
  { civilian: 'Zeus (Mythologie)', undercover: 'Poséidon (Mythologie)' },
  { civilian: 'Hadès (Mythologie)', undercover: 'Arès (Mythologie)' },
  { civilian: 'Athéna (Mythologie)', undercover: 'Artémis (Mythologie)' },
  { civilian: 'Hermès (Mythologie)', undercover: 'Apollon (Mythologie)' },
  { civilian: 'Héra (Mythologie)', undercover: 'Déméter (Mythologie)' },
  { civilian: 'Odin (Mythologie)', undercover: 'Thor (Mythologie)' },
  { civilian: 'Loki (Mythologie)', undercover: 'Freya (Mythologie)' },
  { civilian: 'Anubis (Mythologie)', undercover: 'Râ (Mythologie)' },
  { civilian: 'Medusa (Mythologie)', undercover: 'Sphinx (Mythologie)' },
  { civilian: 'Minotaure (Mythologie)', undercover: 'Cyclope (Mythologie)' },

  // Pokémon
  { civilian: 'Pikachu (Pokémon)', undercover: 'Raichu (Pokémon)' },
  { civilian: 'Salamèche (Pokémon)', undercover: 'Reptincel (Pokémon)' },
  { civilian: 'Carapuce (Pokémon)', undercover: 'Carabaffe (Pokémon)' },
  { civilian: 'Bulbizarre (Pokémon)', undercover: 'Herbizarre (Pokémon)' },
  { civilian: 'Evoli (Pokémon)', undercover: 'Aquali (Pokémon)' },
  { civilian: 'Dracaufeu (Pokémon)', undercover: 'Dracolosse (Pokémon)' },
  { civilian: 'Mew (Pokémon)', undercover: 'Mewtwo (Pokémon)' },
  { civilian: 'Rondoudou (Pokémon)', undercover: 'Grodoudou (Pokémon)' },
  { civilian: 'Lucario (Pokémon)', undercover: 'Zoroark (Pokémon)' },
  { civilian: 'Gengar (Pokémon)', undercover: 'Ectoplasma (Pokémon)' },

  // Adulte
  { civilian: 'Missionnaire', undercover: 'Levrette' },
  { civilian: 'Fellation', undercover: 'Cunnilingus' },
  { civilian: 'Préliminaires', undercover: 'Pénétration' },
  { civilian: 'Sexto', undercover: 'Nude' },
  { civilian: 'Lingerie', undercover: 'Nuisette' },
  { civilian: 'Vibromasseur', undercover: 'Godemichet' },
  { civilian: 'Capote', undercover: 'Préservatif' },
  { civilian: 'Libido', undercover: 'Désir' },
  { civilian: 'Domination', undercover: 'Soumission' },
  { civilian: 'Plan cul', undercover: 'Coup d\'un soir' },

  // Marques de voiture
  { civilian: 'BMW', undercover: 'Audi' },
  { civilian: 'Mercedes', undercover: 'Lexus' },
  { civilian: 'Ferrari', undercover: 'Lamborghini' },
  { civilian: 'Porsche', undercover: 'Maserati' },
  { civilian: 'Bugatti', undercover: 'Koenigsegg' },
  { civilian: 'Tesla', undercover: 'Polestar' },
  { civilian: 'Peugeot', undercover: 'Renault' },
  { civilian: 'Citroen', undercover: 'Fiat' },
  { civilian: 'Toyota', undercover: 'Honda' },
  { civilian: 'Nissan', undercover: 'Mazda' }
];

module.exports = {
  WORD_PAIRS
};


