const WORD_PAIRS = [
  { civilian: 'Chat', undercover: 'Tigre' },
  { civilian: 'Pizza', undercover: 'Lasagne' },
  { civilian: 'Plage', undercover: 'Piscine' },
  { civilian: 'Avion', undercover: 'Helicoptere' },
  { civilian: 'Laptop', undercover: 'Tablette' },
  { civilian: 'Cafe', undercover: 'The' },
  { civilian: 'Football', undercover: 'Rugby' },
  { civilian: 'Neige', undercover: 'Glace' },
  { civilian: 'Lune', undercover: 'Soleil' },
  { civilian: 'Banane', undercover: 'Mangue' },
  { civilian: 'Ocean', undercover: 'Riviere' },
  { civilian: 'Moto', undercover: 'Velo' },
  { civilian: 'Cinema', undercover: 'Theatre' },
  { civilian: 'Paris', undercover: 'Rome' },
  { civilian: 'Boulanger', undercover: 'Patisserie' },
  { civilian: 'Batterie', undercover: 'Guitare' },
  { civilian: 'Docteur', undercover: 'Infirmier' },
  { civilian: 'Chocolat', undercover: 'Vanille' },
  { civilian: 'Montagne', undercover: 'Colline' },
  { civilian: 'Taxi', undercover: 'Bus' },

  // Lieux (faciles)
  { civilian: 'Ecole', undercover: 'College' },
  { civilian: 'Hopital', undercover: 'Clinique' },
  { civilian: 'Supermarche', undercover: 'Epicerie' },
  { civilian: 'Aeroport', undercover: 'Gare' },
  { civilian: 'Bibliotheque', undercover: 'Librairie' },
  { civilian: 'Stade', undercover: 'Gymnase' },
  { civilian: 'Restaurant', undercover: 'Fastfood' },
  { civilian: 'Hotel', undercover: 'Auberge' },
  { civilian: 'Musee', undercover: 'Galerie' },
  { civilian: 'Parc', undercover: 'Jardin' },
  { civilian: 'Foret', undercover: 'Jungle' },
  { civilian: 'Ville', undercover: 'Village' },
  { civilian: 'Metropole', undercover: 'Capitale' },
  { civilian: 'Ile', undercover: 'Peninsule' },
  { civilian: 'Desert', undercover: 'Savane' },
  { civilian: 'Pont', undercover: 'Tunnel' },
  { civilian: 'Port', undercover: 'Marina' },
  { civilian: 'Chateau', undercover: 'Palais' },
  { civilian: 'Temple', undercover: 'Sanctuaire' },
  { civilian: 'Marche', undercover: 'Bazar' },

  // Anime (faciles)
  { civilian: 'Naruto (Perso Anime)', undercover: 'Sasuke (Perso Anime)' },
  { civilian: 'Luffy (Perso Anime)', undercover: 'Zoro (Perso Anime)' },
  { civilian: 'Goku (Perso Anime)', undercover: 'Vegeta (Perso Anime)' },
  { civilian: 'Pikachu (Perso Anime)', undercover: 'Evoli (Perso Anime)' },
  { civilian: 'Saitama (Perso Anime)', undercover: 'Genos (Perso Anime)' },
  { civilian: 'Tanjiro (Perso Anime)', undercover: 'Zenitsu (Perso Anime)' },
  { civilian: 'Nezuko (Perso Anime)', undercover: 'Shinobu (Perso Anime)' },
  { civilian: 'Nami (Perso Anime)', undercover: 'Robin (Perso Anime)' },
  { civilian: 'Mikasa (Perso Anime)', undercover: 'Levi (Perso Anime)' },
  { civilian: 'Eren (Perso Anime)', undercover: 'Armin (Perso Anime)' },
  { civilian: 'Itachi (Perso Anime)', undercover: 'Kakashi (Perso Anime)' },
  { civilian: 'Hinata (Perso Anime)', undercover: 'Sakura (Perso Anime)' },
  { civilian: 'Jiraiya (Perso Anime)', undercover: 'Orochimaru (Perso Anime)' },
  { civilian: 'All Might (Perso Anime)', undercover: 'Deku (Perso Anime)' },
  { civilian: 'Bakugo (Perso Anime)', undercover: 'Todoroki (Perso Anime)' },
  { civilian: 'Gojo (Perso Anime)', undercover: 'Sukuna (Perso Anime)' },
  { civilian: 'Yuji (Perso Anime)', undercover: 'Megumi (Perso Anime)' },
  { civilian: 'Ichigo (Perso Anime)', undercover: 'Rukia (Perso Anime)' },
  { civilian: 'Light (Perso Anime)', undercover: 'L (Perso Anime)' },
  { civilian: 'Natsu (Perso Anime)', undercover: 'Gray (Perso Anime)' },
  { civilian: 'Gon (Perso Anime)', undercover: 'Killua (Perso Anime)' },
  { civilian: 'Hisoka (Perso Anime)', undercover: 'Kurapika (Perso Anime)' },
  { civilian: 'Edward (Perso Anime)', undercover: 'Alphonse (Perso Anime)' },
  { civilian: 'Lelouch (Perso Anime)', undercover: 'Suzaku (Perso Anime)' },
  { civilian: 'Inuyasha (Perso Anime)', undercover: 'Kagome (Perso Anime)' },
  { civilian: 'Rem (Perso Anime)', undercover: 'Emilia (Perso Anime)' },
  { civilian: 'Subaru (Perso Anime)', undercover: 'Otto (Perso Anime)' },
  { civilian: 'Sanji (Perso Anime)', undercover: 'Usopp (Perso Anime)' },
  { civilian: 'Chopper (Perso Anime)', undercover: 'Brook (Perso Anime)' },
  { civilian: 'Franky (Perso Anime)', undercover: 'Jinbe (Perso Anime)' },
  { civilian: 'Ace (Perso Anime)', undercover: 'Sabo (Perso Anime)' },
  { civilian: 'Shanks (Perso Anime)', undercover: 'Mihawk (Perso Anime)' },
  { civilian: 'Law (Perso Anime)', undercover: 'Kid (Perso Anime)' },
  { civilian: 'Yamato (Perso Anime)', undercover: 'Carrot (Perso Anime)' },
  { civilian: 'Gaara (Perso Anime)', undercover: 'Neji (Perso Anime)' },
  { civilian: 'Rock Lee (Perso Anime)', undercover: 'Shikamaru (Perso Anime)' },
  { civilian: 'Tsunade (Perso Anime)', undercover: 'Sakura (Perso Anime)' },
  { civilian: 'Madara (Perso Anime)', undercover: 'Obito (Perso Anime)' },
  { civilian: 'Pain (Perso Anime)', undercover: 'Konan (Perso Anime)' },
  { civilian: 'Minato (Perso Anime)', undercover: 'Kakashi (Perso Anime)' },
  { civilian: 'Hashirama (Perso Anime)', undercover: 'Tobirama (Perso Anime)' },
  { civilian: 'Boruto (Perso Anime)', undercover: 'Sarada (Perso Anime)' },
  { civilian: 'Kawaki (Perso Anime)', undercover: 'Mitsuki (Perso Anime)' },
  { civilian: 'Rengoku (Perso Anime)', undercover: 'Tengen (Perso Anime)' },
  { civilian: 'Muichiro (Perso Anime)', undercover: 'Mitsuri (Perso Anime)' },
  { civilian: 'Inosuke (Perso Anime)', undercover: 'Zenitsu (Perso Anime)' },
  { civilian: 'Asta (Perso Anime)', undercover: 'Yuno (Perso Anime)' },
  { civilian: 'Noelle (Perso Anime)', undercover: 'Mimosa (Perso Anime)' },
  { civilian: 'Eren (Perso Anime)', undercover: 'Reiner (Perso Anime)' },
  { civilian: 'Annie (Perso Anime)', undercover: 'Pieck (Perso Anime)' },
  { civilian: 'Erwin (Perso Anime)', undercover: 'Hange (Perso Anime)' },
  { civilian: 'Kira (Perso Anime)', undercover: 'Ryuk (Perso Anime)' },
  { civilian: 'Near (Perso Anime)', undercover: 'Mello (Perso Anime)' },
  { civilian: 'Yagami (Perso Anime)', undercover: 'L (Perso Anime)' },
  { civilian: 'Gintoki (Perso Anime)', undercover: 'Kagura (Perso Anime)' },
  { civilian: 'Mob (Perso Anime)', undercover: 'Reigen (Perso Anime)' },
  { civilian: 'Koro Sensei (Perso Anime)', undercover: 'Nagisa (Perso Anime)' },
  { civilian: 'Jotaro (Perso Anime)', undercover: 'Dio (Perso Anime)' },
  { civilian: 'Josuke (Perso Anime)', undercover: 'Giorno (Perso Anime)' },
  { civilian: 'Denji (Perso Anime)', undercover: 'Power (Perso Anime)' },
  { civilian: 'Makima (Perso Anime)', undercover: 'Aki (Perso Anime)' },
  { civilian: 'Maomao (Perso Anime)', undercover: 'Jinshi (Perso Anime)' },
  { civilian: 'Gojo (Perso Anime)', undercover: 'Geto (Perso Anime)' },
  { civilian: 'Toji (Perso Anime)', undercover: 'Sukuna (Perso Anime)' },
  { civilian: 'Nanami (Perso Anime)', undercover: 'Todo (Perso Anime)' },
  { civilian: 'Yuta (Perso Anime)', undercover: 'Maki (Perso Anime)' },
  { civilian: 'Kakashi (Perso Anime)', undercover: 'Gai (Perso Anime)' },
  { civilian: 'Obito (Perso Anime)', undercover: 'Madara (Perso Anime)' },
  { civilian: 'Minato (Perso Anime)', undercover: 'Tobirama (Perso Anime)' },
  { civilian: 'Itadori (Perso Anime)', undercover: 'Megumi (Perso Anime)' },
  { civilian: 'Rimuru (Perso Anime)', undercover: 'Diablo (Perso Anime)' },
  { civilian: 'Anya (Perso Anime)', undercover: 'Loid (Perso Anime)' },
  { civilian: 'Yor (Perso Anime)', undercover: 'Fiona (Perso Anime)' },
  { civilian: 'Aizen (Perso Anime)', undercover: 'Urahara (Perso Anime)' },
  { civilian: 'Byakuya (Perso Anime)', undercover: 'Kenpachi (Perso Anime)' },
  { civilian: 'Giyu (Perso Anime)', undercover: 'Rengoku (Perso Anime)' },
  { civilian: 'Tengen (Perso Anime)', undercover: 'Muichiro (Perso Anime)' },
  { civilian: 'Mitsuri (Perso Anime)', undercover: 'Shinobu (Perso Anime)' },
  { civilian: 'Dabi (Perso Anime)', undercover: 'Shigaraki (Perso Anime)' },
  { civilian: 'All For One (Perso Anime)', undercover: 'Endeavor (Perso Anime)' },
  { civilian: 'Sasori (Perso Anime)', undercover: 'Deidara (Perso Anime)' },
  { civilian: 'Kisame (Perso Anime)', undercover: 'Itachi (Perso Anime)' },
  { civilian: 'Kaguya (Perso Anime)', undercover: 'Madara (Perso Anime)' },

  // Titres d anime (categorie dediee)
  { civilian: 'Naruto (Anime)', undercover: 'One Piece (Anime)' },
  { civilian: 'Bleach (Anime)', undercover: 'Fairy Tail (Anime)' },
  { civilian: 'Dragon Ball (Anime)', undercover: 'One Punch Man (Anime)' },
  { civilian: 'Demon Slayer (Anime)', undercover: 'Jujutsu Kaisen (Anime)' },
  { civilian: 'Attack On Titan (Anime)', undercover: 'Death Note (Anime)' },
  { civilian: 'My Hero Academia (Anime)', undercover: 'Black Clover (Anime)' },
  { civilian: 'Chainsaw Man (Anime)', undercover: 'Tokyo Ghoul (Anime)' },
  { civilian: 'Hunter XHunter (Anime)', undercover: 'Yu Yu Hakusho (Anime)' },
  { civilian: 'Code Geass (Anime)', undercover: 'Steins Gate (Anime)' },
  { civilian: 'Spy XFamily (Anime)', undercover: 'Kaguya Sama (Anime)' },
  { civilian: 'Haikyu (Anime)', undercover: 'Kuroko No Basket (Anime)' },
  { civilian: 'Blue Lock (Anime)', undercover: 'Captain Tsubasa (Anime)' },
  { civilian: 'Pokemon (Anime)', undercover: 'Digimon (Anime)' },
  { civilian: 'Jo Jo (Anime)', undercover: 'Baki (Anime)' },
  { civilian: 'Vinland Saga (Anime)', undercover: 'Dr Stone (Anime)' },
  { civilian: 'Solo Leveling (Anime)', undercover: 'Tower Of God (Anime)' },
  { civilian: 'Blue Exorcist (Anime)', undercover: 'Noragami (Anime)' },
  { civilian: 'Fire Force (Anime)', undercover: 'Soul Eater (Anime)' },
  { civilian: 'Mob Psycho (Anime)', undercover: 'One Punch Man (Anime)' },
  { civilian: 'Tokyo Revengers (Anime)', undercover: 'Wind Breaker (Anime)' },
  { civilian: 'Monster (Anime)', undercover: 'Psycho Pass (Anime)' },
  { civilian: 'Black Lagoon (Anime)', undercover: 'Jormungand (Anime)' },
  { civilian: 'Parasyte (Anime)', undercover: 'Ajin (Anime)' },
  { civilian: 'Re Zero (Anime)', undercover: 'Konosuba (Anime)' },
  { civilian: 'Classroom Of The Elite (Anime)', undercover: 'Tomodachi Game (Anime)' },
  { civilian: 'Code Geass (Anime)', undercover: 'Guilty Crown (Anime)' },
  { civilian: 'Hellsing (Anime)', undercover: 'Castlevania (Anime)' },
  { civilian: 'Mushoku Tensei (Anime)', undercover: 'That Time I Got Reincarnated As A Slime (Anime)' },
  { civilian: 'Overlord (Anime)', undercover: 'Log Horizon (Anime)' },
  { civilian: 'Initial D (Anime)', undercover: 'MF Ghost (Anime)' },

  // Lieux d anime (One Piece, Naruto, etc.)
  { civilian: 'Wano', undercover: 'Dressrosa' },
  { civilian: 'Enies Lobby', undercover: 'Marineford' },
  { civilian: 'Whole Cake', undercover: 'Wano' },
  { civilian: 'Skypiea', undercover: 'Alabasta' },
  { civilian: 'Water 7', undercover: 'Enies Lobby' },
  { civilian: 'Punk Hazard', undercover: 'Dressrosa' },
  { civilian: 'Sabaody', undercover: 'Amazon Lily' },
  { civilian: 'Impel Down', undercover: 'Marineford' },
  { civilian: 'Laugh Tale', undercover: 'Raftel' },
  { civilian: 'Loguetown', undercover: 'Shells Town' },
  { civilian: 'Onigashima', undercover: 'Wano' },
  { civilian: 'Zou', undercover: 'Wano' },
  { civilian: 'Jaya', undercover: 'Skypiea' },
  { civilian: 'Konoha', undercover: 'Suna' },
  { civilian: 'Kiri', undercover: 'Kumo' },
  { civilian: 'Iwa', undercover: 'Ame' },
  { civilian: 'Udon (Wano)', undercover: 'Onigashima' },
  { civilian: 'Egghead', undercover: 'Punk Hazard' },
  { civilian: 'Elbaf', undercover: 'Wano' },
  { civilian: 'Hueco Mundo', undercover: 'Soul Society' },
  { civilian: 'Las Noches', undercover: 'Karakura' },
  { civilian: 'Shibuya', undercover: 'Shinjuku' },
  { civilian: 'District Rouge', undercover: 'Mugen Train' },
  { civilian: 'Paradis', undercover: 'Marley' },
  { civilian: 'Wall Maria', undercover: 'Wall Rose' },
  { civilian: 'UA (Lieu Anime)', undercover: 'Shiketsu (Lieu Anime)' },
  { civilian: 'Kamino (Lieu Anime)', undercover: 'Hosu (Lieu Anime)' },
  { civilian: 'Aincrad', undercover: 'Alfheim' },

  // Dessins animes
  { civilian: 'SpongeBob (Dessin Anime)', undercover: 'Patrick (Dessin Anime)' },
  { civilian: 'Bob L Eponge (Dessin Anime)', undercover: 'Carlo (Dessin Anime)' },
  { civilian: 'Les Simpson (Dessin Anime)', undercover: 'Futurama (Dessin Anime)' },
  { civilian: 'Homer (Dessin Anime)', undercover: 'Bart (Dessin Anime)' },
  { civilian: 'Marge (Dessin Anime)', undercover: 'Lisa (Dessin Anime)' },
  { civilian: 'South Park (Dessin Anime)', undercover: 'Family Guy (Dessin Anime)' },
  { civilian: 'Cartman (Dessin Anime)', undercover: 'Kenny (Dessin Anime)' },
  { civilian: 'Stewie (Dessin Anime)', undercover: 'Brian (Dessin Anime)' },
  { civilian: 'American Dad (Dessin Anime)', undercover: 'Rick And Morty (Dessin Anime)' },
  { civilian: 'Rick (Dessin Anime)', undercover: 'Morty (Dessin Anime)' },
  { civilian: 'Scooby Doo (Dessin Anime)', undercover: 'Sammy (Dessin Anime)' },
  { civilian: 'Tom (Dessin Anime)', undercover: 'Jerry (Dessin Anime)' },
  { civilian: 'Titi (Dessin Anime)', undercover: 'Gros Minet (Dessin Anime)' },
  { civilian: 'Bugs Bunny (Dessin Anime)', undercover: 'Daffy Duck (Dessin Anime)' },
  { civilian: 'Road Runner (Dessin Anime)', undercover: 'Coyotte (Dessin Anime)' },
  { civilian: 'Looney Tunes (Dessin Anime)', undercover: 'Merrie Melodies (Dessin Anime)' },
  { civilian: 'Mickey (Dessin Anime)', undercover: 'Donald (Dessin Anime)' },
  { civilian: 'Dingo (Dessin Anime)', undercover: 'Pluto (Dessin Anime)' },
  { civilian: 'Minnie (Dessin Anime)', undercover: 'Daisy (Dessin Anime)' },
  { civilian: 'DuckTales (Dessin Anime)', undercover: 'Picsou (Dessin Anime)' },
  { civilian: 'Tic Et Tac (Dessin Anime)', undercover: 'Riri Fifi Loulou (Dessin Anime)' },
  { civilian: 'Asterix (Dessin Anime)', undercover: 'Obelix (Dessin Anime)' },
  { civilian: 'Idefix (Dessin Anime)', undercover: 'Panoramix (Dessin Anime)' },
  { civilian: 'Lucky Luke (Dessin Anime)', undercover: 'Jolly Jumper (Dessin Anime)' },
  { civilian: 'Les Dalton (Dessin Anime)', undercover: 'Rantanplan (Dessin Anime)' },
  { civilian: 'Inspecteur Gadget (Dessin Anime)', undercover: 'Sophie (Dessin Anime)' },
  { civilian: 'Marsupilami (Dessin Anime)', undercover: 'Spirou (Dessin Anime)' },
  { civilian: 'Titeuf (Dessin Anime)', undercover: 'Nadia (Dessin Anime)' },
  { civilian: 'Code Lyoko (Dessin Anime)', undercover: 'Totally Spies (Dessin Anime)' },
  { civilian: 'Yumi (Dessin Anime)', undercover: 'Ulrich (Dessin Anime)' },
  { civilian: 'Sam Clover Alex (Dessin Anime)', undercover: 'Kim Possible (Dessin Anime)' },
  { civilian: 'Phineas Et Ferb (Dessin Anime)', undercover: 'Candice (Dessin Anime)' },
  { civilian: 'Les Razmoket (Dessin Anime)', undercover: 'Hey Arnold (Dessin Anime)' },
  { civilian: 'Les Zinzins De L Espace (Dessin Anime)', undercover: 'Oggy Et Les Cafards (Dessin Anime)' },
  { civilian: 'Oggy (Dessin Anime)', undercover: 'Jack (Dessin Anime)' },
  { civilian: 'Les Supers Nanas (Dessin Anime)', undercover: 'Dexter (Dessin Anime)' },
  { civilian: 'Johnny Bravo (Dessin Anime)', undercover: 'Le Laboratoire De Dexter (Dessin Anime)' },
  { civilian: 'Ben 10 (Dessin Anime)', undercover: 'Generator Rex (Dessin Anime)' },
  { civilian: 'Teen Titans (Dessin Anime)', undercover: 'Teen Titans Go (Dessin Anime)' },
  { civilian: 'Robin (Dessin Anime)', undercover: 'Starfire (Dessin Anime)' },
  { civilian: 'Batman The Animated Series (Dessin Anime)', undercover: 'Justice League (Dessin Anime)' },
  { civilian: 'Superman (Dessin Anime)', undercover: 'Batman (Dessin Anime)' },
  { civilian: 'Avatar Le Dernier Maitre De L Air (Dessin Anime)', undercover: 'La Legende De Korra (Dessin Anime)' },
  { civilian: 'Aang (Dessin Anime)', undercover: 'Zuko (Dessin Anime)' },
  { civilian: 'Katara (Dessin Anime)', undercover: 'Toph (Dessin Anime)' },
  { civilian: 'Adventure Time (Dessin Anime)', undercover: 'Regular Show (Dessin Anime)' },
  { civilian: 'Finn (Dessin Anime)', undercover: 'Jake (Dessin Anime)' },
  { civilian: 'Gumball (Dessin Anime)', undercover: 'Darwin (Dessin Anime)' },
  { civilian: 'Clarence (Dessin Anime)', undercover: 'Steven Universe (Dessin Anime)' },
  { civilian: 'Steven Universe (Dessin Anime)', undercover: 'Amethyst (Dessin Anime)' },
  { civilian: 'Miraculous (Dessin Anime)', undercover: 'Ladybug (Dessin Anime)' },
  { civilian: 'Chat Noir (Dessin Anime)', undercover: 'Papillon (Dessin Anime)' },
  { civilian: 'Winx Club (Dessin Anime)', undercover: 'WITCH (Dessin Anime)' },
  { civilian: 'Bloom (Dessin Anime)', undercover: 'Stella (Dessin Anime)' },
  { civilian: 'Dragon Hunters (Dessin Anime)', undercover: 'Wakfu (Dessin Anime)' },
  { civilian: 'Wakfu (Dessin Anime)', undercover: 'Dofus (Dessin Anime)' },
  { civilian: 'Yugo (Dessin Anime)', undercover: 'Tristepin (Dessin Anime)' },
  { civilian: 'Princesse Sofia (Dessin Anime)', undercover: 'Raiponce Serie (Dessin Anime)' },
  { civilian: 'Peppa Pig (Dessin Anime)', undercover: 'George (Dessin Anime)' },
  { civilian: 'Pat Patrouille (Dessin Anime)', undercover: 'Ryder (Dessin Anime)' },
  { civilian: 'Chase (Dessin Anime)', undercover: 'Marcus (Dessin Anime)' },
  { civilian: 'Bluey (Dessin Anime)', undercover: 'Bingo (Dessin Anime)' },
  { civilian: 'Dora L Exploratrice (Dessin Anime)', undercover: 'Babouche (Dessin Anime)' },
  { civilian: 'Diego (Dessin Anime)', undercover: 'Dora (Dessin Anime)' },
  { civilian: 'Les Schtroumpfs (Dessin Anime)', undercover: 'Gargamel (Dessin Anime)' },
  { civilian: 'Schtroumpfette (Dessin Anime)', undercover: 'Grand Schtroumpf (Dessin Anime)' },
  { civilian: 'Heidi (Dessin Anime)', undercover: 'Remi Sans Famille (Dessin Anime)' },
  { civilian: 'Inspecteur Colombo Dessin (Dessin Anime)', undercover: 'Sherlock Holmes Dessin (Dessin Anime)' },
  { civilian: 'Les Minijusticiers (Dessin Anime)', undercover: 'Martin Mystere (Dessin Anime)' },
  { civilian: 'Martin Mystere (Dessin Anime)', undercover: 'Totally Spies (Dessin Anime)' },
  { civilian: 'Galactik Football (Dessin Anime)', undercover: 'Foot 2 Rue (Dessin Anime)' },
  { civilian: 'Code Name Kids Next Door (Dessin Anime)', undercover: 'Samurai Jack (Dessin Anime)' },
  { civilian: 'Samurai Jack (Dessin Anime)', undercover: 'Primal (Dessin Anime)' },
  { civilian: 'The Owl House (Dessin Anime)', undercover: 'Gravity Falls (Dessin Anime)' },
  { civilian: 'Dipper (Dessin Anime)', undercover: 'Mabel (Dessin Anime)' },
  { civilian: 'Star Vs The Forces Of Evil (Dessin Anime)', undercover: 'Amphibia (Dessin Anime)' },
  { civilian: 'Big Hero 6 Serie (Dessin Anime)', undercover: 'Baymax (Dessin Anime)' },
  { civilian: 'Les Pyjamasques (Dessin Anime)', undercover: 'Miraculous (Dessin Anime)' },

  // Personnages de dessins animes
  { civilian: 'Bob L Eponge (Personnage)', undercover: 'Patrick (Personnage)' },
  { civilian: 'Carlo (Personnage)', undercover: 'Mr Krabs (Personnage)' },
  { civilian: 'Homer Simpson (Personnage)', undercover: 'Bart Simpson (Personnage)' },
  { civilian: 'Marge Simpson (Personnage)', undercover: 'Lisa Simpson (Personnage)' },
  { civilian: 'Stewie Griffin (Personnage)', undercover: 'Brian Griffin (Personnage)' },
  { civilian: 'Peter Griffin (Personnage)', undercover: 'Lois Griffin (Personnage)' },
  { civilian: 'Rick Sanchez (Personnage)', undercover: 'Morty Smith (Personnage)' },
  { civilian: 'Summer Smith (Personnage)', undercover: 'Beth Smith (Personnage)' },
  { civilian: 'Scooby Doo (Personnage)', undercover: 'Sammy (Personnage)' },
  { civilian: 'Vera (Personnage)', undercover: 'Daphné (Personnage)' },
  { civilian: 'Tom (Personnage)', undercover: 'Jerry (Personnage)' },
  { civilian: 'Spike (Personnage)', undercover: 'Tyke (Personnage)' },
  { civilian: 'Bugs Bunny (Personnage)', undercover: 'Daffy Duck (Personnage)' },
  { civilian: 'Titi (Personnage)', undercover: 'Gros Minet (Personnage)' },
  { civilian: 'Mickey (Personnage)', undercover: 'Donald (Personnage)' },
  { civilian: 'Dingo (Personnage)', undercover: 'Pluto (Personnage)' },
  { civilian: 'Minnie (Personnage)', undercover: 'Daisy (Personnage)' },
  { civilian: 'Picsou (Personnage)', undercover: 'Flagada Jones (Personnage)' },
  { civilian: 'Asterix (Personnage)', undercover: 'Obelix (Personnage)' },
  { civilian: 'Panoramix (Personnage)', undercover: 'Idefix (Personnage)' },
  { civilian: 'Lucky Luke (Personnage)', undercover: 'Jolly Jumper (Personnage)' },
  { civilian: 'Joe Dalton (Personnage)', undercover: 'Averell Dalton (Personnage)' },
  { civilian: 'Inspecteur Gadget (Personnage)', undercover: 'Sophie (Personnage)' },
  { civilian: 'Gadgeto Copter (Personnage)', undercover: 'Docteur Gang (Personnage)' },
  { civilian: 'Sacha (Personnage)', undercover: 'Pikachu (Personnage)' },
  { civilian: 'Ondine (Personnage)', undercover: 'Pierre (Personnage)' },
  { civilian: 'Jessie (Personnage)', undercover: 'James (Personnage)' },
  { civilian: 'Aang (Personnage)', undercover: 'Katara (Personnage)' },
  { civilian: 'Sokka (Personnage)', undercover: 'Toph (Personnage)' },
  { civilian: 'Zuko (Personnage)', undercover: 'Azula (Personnage)' },
  { civilian: 'Finn (Personnage)', undercover: 'Jake (Personnage)' },
  { civilian: 'Princesse Bubblegum (Personnage)', undercover: 'Marceline (Personnage)' },
  { civilian: 'Gumball (Personnage)', undercover: 'Darwin (Personnage)' },
  { civilian: 'Anais (Personnage)', undercover: 'Richard (Personnage)' },
  { civilian: 'Ladybug (Personnage)', undercover: 'Chat Noir (Personnage)' },
  { civilian: 'Papillon (Personnage)', undercover: 'Rena Rouge (Personnage)' },
  { civilian: 'Bloom (Personnage)', undercover: 'Stella (Personnage)' },
  { civilian: 'Flora (Personnage)', undercover: 'Musa (Personnage)' },
  { civilian: 'Yugo (Personnage)', undercover: 'Tristepin (Personnage)' },
  { civilian: 'Amalia (Personnage)', undercover: 'Ruel (Personnage)' },
  { civilian: 'Chase (Personnage)', undercover: 'Marcus (Personnage)' },
  { civilian: 'Ruben (Personnage)', undercover: 'Stella Pat Patrouille (Personnage)' },
  { civilian: 'Bluey (Personnage)', undercover: 'Bingo (Personnage)' },
  { civilian: 'Bandit (Personnage)', undercover: 'Chilli (Personnage)' },

  // Techniques anime
  { civilian: 'Rasengan (Technique Anime)', undercover: 'Chidori (Technique Anime)' },
  { civilian: 'Kamehameha (Technique Anime)', undercover: 'Final Flash (Technique Anime)' },
  { civilian: 'Bankai (Technique Anime)', undercover: 'Shikai (Technique Anime)' },
  { civilian: 'Domain Expansion (Technique Anime)', undercover: 'Cursed Technique (Technique Anime)' },
  { civilian: 'Haki Observation (Technique Anime)', undercover: 'Haki Armement (Technique Anime)' },
  { civilian: 'Gear 4 (Technique Anime)', undercover: 'Gear 5 (Technique Anime)' },
  { civilian: 'Souffle Eau (Technique Anime)', undercover: 'Souffle Feu (Technique Anime)' },
  { civilian: 'Sharingan (Technique Anime)', undercover: 'Byakugan (Technique Anime)' },
  { civilian: 'Mangekyo (Technique Anime)', undercover: 'Rinnegan (Technique Anime)' },
  { civilian: 'Kaioken (Technique Anime)', undercover: 'Ultra Instinct (Technique Anime)' },
  { civilian: 'One For All (Technique Anime)', undercover: 'All For One (Technique Anime)' },
  { civilian: 'Black Flash (Technique Anime)', undercover: 'Purple (Technique Anime)' },
  { civilian: 'Getsuga Tensho (Technique Anime)', undercover: 'Cero (Technique Anime)' },
  { civilian: 'Susanoo (Technique Anime)', undercover: 'Amaterasu (Technique Anime)' },
  { civilian: 'Multi Clonage (Technique Anime)', undercover: 'Substitution (Technique Anime)' },

  // Films connus
  { civilian: 'Titanic', undercover: 'Avatar' },
  { civilian: 'Avatar', undercover: 'Avengers' },
  { civilian: 'Interstellar', undercover: 'Inception' },
  { civilian: 'Inception', undercover: 'Tenet' },
  { civilian: 'Joker', undercover: 'Batman' },
  { civilian: 'Batman', undercover: 'Superman' },
  { civilian: 'Spider Man', undercover: 'Iron Man' },
  { civilian: 'Thor', undercover: 'Loki' },
  { civilian: 'Black Panther', undercover: 'Doctor Strange' },
  { civilian: 'Matrix', undercover: 'John Wick' },
  { civilian: 'Gladiator', undercover: 'Troie' },
  { civilian: 'Harry Potter', undercover: 'Le Seigneur Des Anneaux' },
  { civilian: 'Star Wars', undercover: 'Star Trek' },
  { civilian: 'Fast And Furious', undercover: 'Transformers' },
  { civilian: 'Mission Impossible', undercover: 'James Bond' },
  { civilian: 'Le Roi Lion', undercover: 'Aladdin' },
  { civilian: 'Toy Story', undercover: 'Cars' },
  { civilian: 'Shrek', undercover: 'Kung Fu Panda' },
  { civilian: 'Frozen', undercover: 'Raiponce' },
  { civilian: 'Scream', undercover: 'Conjuring' },
  { civilian: 'Le Parrain', undercover: 'Les Affranchis' },
  { civilian: 'Scarface', undercover: 'Casino' },
  { civilian: 'Pulp Fiction', undercover: 'Reservoir Dogs' },
  { civilian: 'Fight Club', undercover: 'Seven' },
  { civilian: 'La Ligne Verte', undercover: 'Forrest Gump' },
  { civilian: 'Le Loup De Wall Street', undercover: 'American Psycho' },
  { civilian: 'Le Prestige', undercover: 'Insaisissables' },
  { civilian: 'Shutter Island', undercover: 'Gone Girl' },
  { civilian: 'Le Silence Des Agneaux', undercover: 'Zodiac' },
  { civilian: 'Le Sixieme Sens', undercover: 'Split' },
  { civilian: 'Jurassic Park', undercover: 'King Kong' },
  { civilian: 'Godzilla', undercover: 'Pacific Rim' },
  { civilian: 'Pirates Des Caraibes', undercover: 'Le Masque De Zorro' },
  { civilian: 'Le Monde De Narnia', undercover: 'A La Croisee Des Mondes' },
  { civilian: 'Mad Max', undercover: 'Blade Runner' },
  { civilian: 'Terminator', undercover: 'Robocop' },
  { civilian: 'Alien', undercover: 'Predator' },
  { civilian: 'Dune', undercover: 'Star Wars' },
  { civilian: 'Le Hobbit', undercover: 'Le Seigneur Des Anneaux' },
  { civilian: 'E.T.', undercover: 'Rencontres Du Troisieme Type' },
  { civilian: 'Retour Vers Le Futur', undercover: 'Ready Player One' },
  { civilian: 'Tron', undercover: 'Matrix' },
  { civilian: 'Maman J Ai Rate L Avion', undercover: 'Beethoven' },
  { civilian: 'Le Diner De Cons', undercover: 'La Cite De La Peur' },
  { civilian: 'Les Tuche', undercover: 'Camping' },
  { civilian: 'Intouchables', undercover: 'Le Sens De La Fete' },
  { civilian: 'OSS 117', undercover: 'Asterix Et Obelix' },
  { civilian: 'Taken', undercover: 'Equalizer' },
  { civilian: 'John Wick', undercover: 'Nobody' },
  { civilian: 'Top Gun', undercover: 'Pearl Harbor' },
  { civilian: 'World War Z', undercover: 'Je Suis Une Legende' },
  { civilian: 'Saw', undercover: 'Hostel' },
  { civilian: 'Insidious', undercover: 'Conjuring' },
  { civilian: 'Annabelle', undercover: 'Chucky' },
  { civilian: 'It', undercover: 'Ca' },
  { civilian: 'The Batman', undercover: 'Joker' },
  { civilian: 'Deadpool', undercover: 'Venom' },
  { civilian: 'X Men', undercover: 'Fantastic Four' },
  { civilian: 'Hunger Games', undercover: 'Divergente' },
  { civilian: 'Le Labyrinthe', undercover: 'Hunger Games' },
  { civilian: 'Twilight', undercover: 'Vampire Academy' },
  { civilian: 'Fast X', undercover: 'Need For Speed' },
  { civilian: 'Baby Driver', undercover: 'Drive' },
  { civilian: 'Now You See Me', undercover: 'Le Prestige' },
  { civilian: 'Le Roi Arthur', undercover: 'Robin Des Bois' },
  { civilian: '300', undercover: 'Gladiator' },

  // Personnages connus de films
  { civilian: 'Harry Potter (Perso Film)', undercover: 'Hermione (Perso Film)' },
  { civilian: 'Ron Weasley (Perso Film)', undercover: 'Draco Malfoy (Perso Film)' },
  { civilian: 'Voldemort (Perso Film)', undercover: 'Dumbledore (Perso Film)' },
  { civilian: 'Frodon (Perso Film)', undercover: 'Sam (Perso Film)' },
  { civilian: 'Aragorn (Perso Film)', undercover: 'Legolas (Perso Film)' },
  { civilian: 'Gandalf (Perso Film)', undercover: 'Saroumane (Perso Film)' },
  { civilian: 'Luke Skywalker (Perso Film)', undercover: 'Han Solo (Perso Film)' },
  { civilian: 'Dark Vador (Perso Film)', undercover: 'Obi Wan (Perso Film)' },
  { civilian: 'Leia (Perso Film)', undercover: 'Padme (Perso Film)' },
  { civilian: 'Tony Stark (Perso Film)', undercover: 'Steve Rogers (Perso Film)' },
  { civilian: 'Thor (Perso Film)', undercover: 'Loki (Perso Film)' },
  { civilian: 'Thanos (Perso Film)', undercover: 'Ultron (Perso Film)' },
  { civilian: 'Peter Parker (Perso Film)', undercover: 'Miles Morales (Perso Film)' },
  { civilian: 'Bruce Wayne (Perso Film)', undercover: 'Clark Kent (Perso Film)' },
  { civilian: 'Joker (Perso Film)', undercover: 'Harley Quinn (Perso Film)' },
  { civilian: 'Neo (Perso Film)', undercover: 'Morpheus (Perso Film)' },
  { civilian: 'John Wick (Perso Film)', undercover: 'Jason Bourne (Perso Film)' },
  { civilian: 'Jack Sparrow (Perso Film)', undercover: 'Will Turner (Perso Film)' },
  { civilian: 'Indiana Jones (Perso Film)', undercover: 'Lara Croft (Perso Film)' },
  { civilian: 'Maximus (Perso Film)', undercover: 'Achille (Perso Film)' },
  { civilian: 'Elsa (Perso Film)', undercover: 'Anna (Perso Film)' },
  { civilian: 'Simba (Perso Film)', undercover: 'Mufasa (Perso Film)' },
  { civilian: 'Shrek (Perso Film)', undercover: 'Fiona (Perso Film)' },
  { civilian: 'Po (Perso Film)', undercover: 'Shifu (Perso Film)' },
  { civilian: 'Woody (Perso Film)', undercover: 'Buzz (Perso Film)' },
  { civilian: 'Lightning Mc Queen (Perso Film)', undercover: 'Martin (Perso Film)' },
  { civilian: 'Katniss (Perso Film)', undercover: 'Peeta (Perso Film)' },
  { civilian: 'Deadpool (Perso Film)', undercover: 'Wolverine (Perso Film)' },
  { civilian: 'Rambo (Perso Film)', undercover: 'Rocky (Perso Film)' },
  { civilian: 'Forrest Gump (Perso Film)', undercover: 'Benjamin Button (Perso Film)' },


  // Jeux video / personnages connus
  { civilian: 'Mario', undercover: 'Luigi' },
  { civilian: 'Peach', undercover: 'Daisy' },
  { civilian: 'Bowser', undercover: 'Wario' },
  { civilian: 'Zelda', undercover: 'Link' },
  { civilian: 'Ganondorf', undercover: 'Zelda' },
  { civilian: 'Kirby', undercover: 'Meta Knight' },
  { civilian: 'Sonic', undercover: 'Shadow' },
  { civilian: 'Tails', undercover: 'Knuckles' },
  { civilian: 'Pikachu', undercover: 'Charizard' },
  { civilian: 'Mewtwo', undercover: 'Lucario' },
  { civilian: 'Steve', undercover: 'Creeper' },
  { civilian: 'Herobrine', undercover: 'Enderman' },
  { civilian: 'Fortnite', undercover: 'Apex' },
  { civilian: 'Valorant', undercover: 'CS 2' },
  { civilian: 'League Of Legends', undercover: 'Dota 2' },
  { civilian: 'Overwatch', undercover: 'Paladins' },
  { civilian: 'Call Of Duty', undercover: 'Battlefield' },
  { civilian: 'GTA', undercover: 'Watch Dogs' },
  { civilian: 'Red Dead', undercover: 'GTA' },
  { civilian: 'Kratos', undercover: 'Atreus' },
  { civilian: 'Master Chief', undercover: 'Doomguy' },
  { civilian: 'Lara Croft', undercover: 'Nathan Drake' },
  { civilian: 'Geralt', undercover: 'Ciri' },
  { civilian: 'Arthur Morgan', undercover: 'John Marston' },
  { civilian: 'Ezio', undercover: 'Altair' },
  { civilian: 'Pac Man', undercover: 'Bomberman' },
  { civilian: 'Among Us', undercover: 'Fall Guys' },
  { civilian: 'Brawl Stars', undercover: 'Clash Royale' },
  { civilian: 'Clash Of Clans', undercover: 'Boom Beach' },
  { civilian: 'FIFA', undercover: 'e Football' },
  { civilian: 'Rocket League', undercover: 'Trackmania' },
  { civilian: 'Roblox', undercover: 'Minecraft' },

  // Series / persos de series tres connus
  { civilian: 'Walter White (Perso Série)', undercover: 'Jesse Pinkman (Perso Série)' },
  { civilian: 'Saul Goodman (Perso Série)', undercover: 'Gus Fring (Perso Série)' },
  { civilian: 'Jon Snow (Perso Série)', undercover: 'Daenerys (Perso Série)' },
  { civilian: 'Tyrion (Perso Série)', undercover: 'Arya (Perso Série)' },
  { civilian: 'Eleven (Perso Série)', undercover: 'Mike (Perso Série)' },
  { civilian: 'Dustin (Perso Série)', undercover: 'Will (Perso Série)' },
  { civilian: 'Sherlock (Perso Série)', undercover: 'Watson (Perso Série)' },
  { civilian: 'Michael Scott (Perso Série)', undercover: 'Dwight (Perso Série)' },
  { civilian: 'Ross (Perso Série)', undercover: 'Chandler (Perso Série)' },
  { civilian: 'Monica (Perso Série)', undercover: 'Rachel (Perso Série)' },
  { civilian: 'Barney (Perso Série)', undercover: 'Ted (Perso Série)' },
  { civilian: 'House (Perso Série)', undercover: 'Wilson (Perso Série)' },
  { civilian: 'Rick (Perso Série)', undercover: 'Daryl (Perso Série)' },
  { civilian: 'Meredith (Perso Série)', undercover: 'Cristina (Perso Série)' },
  { civilian: 'Tokyo (Perso Série)', undercover: 'Nairobi (Perso Série)' },
  { civilian: 'Professor (Perso Série)', undercover: 'Berlin (Perso Série)' },
  { civilian: 'Homelander (Perso Série)', undercover: 'Butcher (Perso Série)' },
  { civilian: 'Loki (Perso Série)', undercover: 'Sylvie (Perso Série)' },
  { civilian: 'Wednesday (Perso Série)', undercover: 'Enid (Perso Série)' },
  { civilian: 'Lucifer (Perso Série)', undercover: 'Chloe (Perso Série)' },

  // Villes et lieux (supplementaires)
  { civilian: 'Paris (Ville)', undercover: 'Lyon (Ville)' },
  { civilian: 'Marseille (Ville)', undercover: 'Nice (Ville)' },
  { civilian: 'Toulouse (Ville)', undercover: 'Bordeaux (Ville)' },
  { civilian: 'Lille (Ville)', undercover: 'Nantes (Ville)' },
  { civilian: 'Strasbourg (Ville)', undercover: 'Metz (Ville)' },
  { civilian: 'Bruxelles (Ville)', undercover: 'Amsterdam (Ville)' },
  { civilian: 'Madrid (Ville)', undercover: 'Barcelone (Ville)' },
  { civilian: 'Lisbonne (Ville)', undercover: 'Porto (Ville)' },
  { civilian: 'Londres (Ville)', undercover: 'Manchester (Ville)' },
  { civilian: 'Dublin (Ville)', undercover: 'Belfast (Ville)' },
  { civilian: 'Rome (Ville)', undercover: 'Milan (Ville)' },
  { civilian: 'Naples (Ville)', undercover: 'Florence (Ville)' },
  { civilian: 'Berlin (Ville)', undercover: 'Munich (Ville)' },
  { civilian: 'Vienne (Ville)', undercover: 'Prague (Ville)' },
  { civilian: 'Budapest (Ville)', undercover: 'Varsovie (Ville)' },
  { civilian: 'Athenes (Ville)', undercover: 'Istanbul (Ville)' },
  { civilian: 'New York (Ville)', undercover: 'Chicago (Ville)' },
  { civilian: 'Los Angeles (Ville)', undercover: 'San Francisco (Ville)' },
  { civilian: 'Toronto (Ville)', undercover: 'Montreal (Ville)' },
  { civilian: 'Mexico (Ville)', undercover: 'Bogota (Ville)' },
  { civilian: 'Rio (Ville)', undercover: 'Sao Paulo (Ville)' },
  { civilian: 'Buenos Aires (Ville)', undercover: 'Santiago (Ville)' },
  { civilian: 'Le Caire (Ville)', undercover: 'Casablanca (Ville)' },
  { civilian: 'Dubai (Ville)', undercover: 'Doha (Ville)' },
  { civilian: 'Tokyo (Ville)', undercover: 'Osaka (Ville)' },
  { civilian: 'Seoul (Ville)', undercover: 'Busan (Ville)' },
  { civilian: 'Pekin (Ville)', undercover: 'Shanghai (Ville)' },
  { civilian: 'Hong Kong (Ville)', undercover: 'Taipei (Ville)' },
  { civilian: 'Bangkok (Ville)', undercover: 'Singapour (Ville)' },
  { civilian: 'Sydney (Ville)', undercover: 'Melbourne (Ville)' },

  { civilian: 'École', undercover: 'Université' },
  { civilian: 'Hôpital', undercover: 'Clinique' },
  { civilian: 'Pharmacie', undercover: 'Laboratoire' },
  { civilian: 'Boulangerie', undercover: 'Pâtisserie' },
  { civilian: 'Supermarché', undercover: 'Hypermarché' },
  { civilian: 'Bibliothèque', undercover: 'Médiathèque' },
  { civilian: 'Mairie', undercover: 'Préfecture' },
  { civilian: 'Commissariat', undercover: 'Gendarmerie' },
  { civilian: 'Caserne', undercover: 'Base militaire' },
  { civilian: 'Stade', undercover: 'Gymnase' },
  { civilian: 'Piscine', undercover: 'Patinoire' },
  { civilian: 'Cinéma', undercover: 'Théâtre' },
  { civilian: 'Musée', undercover: 'Galerie' },
  { civilian: 'Parc', undercover: 'Jardin' },
  { civilian: 'Forêt', undercover: 'Bois' },
  { civilian: 'Montagne', undercover: 'Colline' },
  { civilian: 'Plage', undercover: 'Crique' },
  { civilian: 'Lac', undercover: 'Étang' },
  { civilian: 'Rivière', undercover: 'Fleuve' },
  { civilian: 'Port', undercover: 'Marina' },
  { civilian: 'Aéroport', undercover: 'Gare' },
  { civilian: 'Station métro', undercover: 'Arrêt de bus' },
  { civilian: 'Hôtel', undercover: 'Auberge' },
  { civilian: 'Camping', undercover: 'Village vacances' },
  { civilian: 'Château', undercover: 'Palais' },
  { civilian: 'Temple', undercover: 'Église' },
  { civilian: 'Mosquée', undercover: 'Cathédrale' },
  { civilian: 'Marché', undercover: 'Centre commercial' },
  { civilian: 'Pont', undercover: 'Tunnel' },
  { civilian: 'Île', undercover: 'Péninsule' },
  { civilian: 'Stylo', undercover: 'Crayon' },
  { civilian: 'Gomme', undercover: 'Taille Crayon' },
  { civilian: 'Cahier', undercover: 'Agenda' },
  { civilian: 'Sac ADos', undercover: 'Valise' },
  { civilian: 'Bouteille', undercover: 'Gourde' },
  { civilian: 'Verre', undercover: 'Tasse' },
  { civilian: 'Assiette', undercover: 'Bol' },
  { civilian: 'Cuillere', undercover: 'Fourchette' },
  { civilian: 'Couteau', undercover: 'Econome' },
  { civilian: 'Poele', undercover: 'Casserole' },
  { civilian: 'Mixer', undercover: 'Blender' },
  { civilian: 'Lampe', undercover: 'Ampoule' },
  { civilian: 'Chargeur', undercover: 'Cable USB' },
  { civilian: 'Ecouteurs', undercover: 'Casque' },
  { civilian: 'Clavier', undercover: 'Souris' },
  { civilian: 'Telecommande', undercover: 'Manette' },
  { civilian: 'Horloge', undercover: 'Montre' },
  { civilian: 'Parapluie', undercover: 'Kway' },
  { civilian: 'Cle', undercover: 'Serrure' },
  { civilian: 'Pinceau', undercover: 'Rouleau' },

  // Metiers (proches)
  { civilian: 'Pompier', undercover: 'Policier' },
  { civilian: 'Boulanger', undercover: 'Patissier' },
  { civilian: 'Professeur', undercover: 'Instituteur' },
  { civilian: 'Medecin', undercover: 'Chirurgien' },
  { civilian: 'Infirmier', undercover: 'Aide Soignant' },
  { civilian: 'Veterinaire', undercover: 'Toiletteur' },
  { civilian: 'Pilote', undercover: 'Steward' },
  { civilian: 'Chauffeur', undercover: 'Livreur' },
  { civilian: 'Cuisinier', undercover: 'Chef' },
  { civilian: 'Serveur', undercover: 'Barman' },
  { civilian: 'Architecte', undercover: 'Ingenieur' },
  { civilian: 'Macon', undercover: 'Plombier' },
  { civilian: 'Electricien', undercover: 'Technicien' },
  { civilian: 'Journaliste', undercover: 'Presentateur' },
  { civilian: 'Photographe', undercover: 'Cameraman' },
  { civilian: 'Acteur', undercover: 'Cascadeur' },
  { civilian: 'Chanteur', undercover: 'Rappeur' },
  { civilian: 'Avocat', undercover: 'Juge' },
  { civilian: 'Banquier', undercover: 'Comptable' },
  { civilian: 'Coiffeur', undercover: 'Barbier' },

  // Nourriture
  { civilian: 'Hamburger', undercover: 'Cheeseburger' },
  { civilian: 'Frites', undercover: 'Potatoes' },
  { civilian: 'Riz', undercover: 'Pates' },
  { civilian: 'Poulet', undercover: 'Dinde' },
  { civilian: 'Steak', undercover: 'Escalope' },
  { civilian: 'Saumon', undercover: 'Thon' },
  { civilian: 'Pomme', undercover: 'Poire' },
  { civilian: 'Orange', undercover: 'Mandarine' },
  { civilian: 'Fraise', undercover: 'Framboise' },
  { civilian: 'Biscuit', undercover: 'Gateau' },
  { civilian: 'Glace', undercover: 'Sorbet' },
  { civilian: 'Yaourt', undercover: 'Fromage Blanc' },
  { civilian: 'Lait', undercover: 'Creme' },
  { civilian: 'Eau', undercover: 'Jus' },
  { civilian: 'Soda', undercover: 'Limonade' },

  // Animaux
  { civilian: 'Chien', undercover: 'Loup' },
  { civilian: 'Lion', undercover: 'Leopard' },
  { civilian: 'Cheval', undercover: 'Poney' },
  { civilian: 'Vache', undercover: 'Taureau' },
  { civilian: 'Mouton', undercover: 'Chevre' },
  { civilian: 'Lapin', undercover: 'Lièvre' },
  { civilian: 'Canard', undercover: 'Oie' },
  { civilian: 'Poule', undercover: 'Dinde' },
  { civilian: 'Aigle', undercover: 'Faucon' },
  { civilian: 'Requin', undercover: 'Dauphin' },
  { civilian: 'Baleine', undercover: 'Orque' },
  { civilian: 'Tortue', undercover: 'Crocodile' },
  { civilian: 'Serpent', undercover: 'Iguane' },
  { civilian: 'Abeille', undercover: 'Guêpe' },
  { civilian: 'Papillon', undercover: 'Libellule' },

  // Transports
  { civilian: 'Voiture', undercover: 'Camion' },
  { civilian: 'Scooter', undercover: 'Moto' },
  { civilian: 'Tram', undercover: 'Metro' },
  { civilian: 'Train', undercover: 'TGV' },
  { civilian: 'Bateau', undercover: 'Yacht' },
  { civilian: 'Voilier', undercover: 'Catamaran' },
  { civilian: 'Fusee', undercover: 'Navette' },
  { civilian: 'Drone', undercover: 'Helicoptere' },
  { civilian: 'Skate', undercover: 'Trottinette' },
  { civilian: 'Roller', undercover: 'Skate' },

  // Sports
  { civilian: 'Tennis', undercover: 'Padel' },
  { civilian: 'Basket', undercover: 'Handball' },
  { civilian: 'Volley', undercover: 'Badminton' },
  { civilian: 'Natation', undercover: 'Plongeon' },
  { civilian: 'Boxe', undercover: 'MMA' },
  { civilian: 'Judo', undercover: 'Karate' },
  { civilian: 'Ski', undercover: 'Snowboard' },
  { civilian: 'Surf', undercover: 'Bodyboard' },
  { civilian: 'Cyclisme', undercover: 'VTT' },
  { civilian: 'Athletisme', undercover: 'Triathlon' },

  // Maison / quotidien
  { civilian: 'Canape', undercover: 'Fauteuil' },
  { civilian: 'Lit', undercover: 'Canape Lit' },
  { civilian: 'Oreiller', undercover: 'Coussin' },
  { civilian: 'Couette', undercover: 'Plaid' },
  { civilian: 'Table', undercover: 'Bureau' },
  { civilian: 'Chaise', undercover: 'Tabouret' },
  { civilian: 'Armoire', undercover: 'Commode' },
  { civilian: 'Miroir', undercover: 'Cadre' },
  { civilian: 'Frigo', undercover: 'Congelateur' },
  { civilian: 'Four', undercover: 'Micro Ondes' },
  { civilian: 'Lave Linge', undercover: 'Lave Vaisselle' },
  { civilian: 'Balai', undercover: 'Aspirateur' },
  { civilian: 'Savon', undercover: 'Shampoing' },
  { civilian: 'Dentifrice', undercover: 'Bain De Bouche' },
  { civilian: 'Serviette', undercover: 'Peignoir' },

  // Vetements / accessoires
  { civilian: 'TShirt', undercover: 'Polo' },
  { civilian: 'Chemise', undercover: 'Blouse' },
  { civilian: 'Jean', undercover: 'Pantalon' },
  { civilian: 'Short', undercover: 'Bermuda' },
  { civilian: 'Jupe', undercover: 'Robe' },
  { civilian: 'Veste', undercover: 'Manteau' },
  { civilian: 'Pull', undercover: 'Sweat' },
  { civilian: 'Baskets', undercover: 'Chaussures' },
  { civilian: 'Bonnet', undercover: 'Casquette' },
  { civilian: 'Lunettes', undercover: 'Lentilles' },
  { civilian: 'Sac', undercover: 'Pochette' },
  { civilian: 'Ceinture', undercover: 'Bretelles' },

  // Tech / internet
  { civilian: 'Google', undercover: 'Bing' },
  { civilian: 'You Tube', undercover: 'Twitch' },
  { civilian: 'Instagram', undercover: 'Tik Tok' },
  { civilian: 'Discord', undercover: 'Teamspeak' },
  { civilian: 'Whats App', undercover: 'Telegram' },
  { civilian: 'Netflix', undercover: 'Prime Video' },
  { civilian: 'Spotify', undercover: 'Deezer' },
  { civilian: 'Windows', undercover: 'Linux' },
  { civilian: 'Android', undercover: 'i OS' },
  { civilian: 'Wi Fi', undercover: '4 G' },

  // Musique / instruments
  { civilian: 'Piano', undercover: 'Synthé' },
  { civilian: 'Violon', undercover: 'Alto' },
  { civilian: 'Batterie', undercover: 'Percussion' },
  { civilian: 'Saxophone', undercover: 'Trompette' },
  { civilian: 'Flute', undercover: 'Clarinette' },
  { civilian: 'Concert', undercover: 'Festival' },
  { civilian: 'DJ', undercover: 'Producteur' },
  { civilian: 'Album', undercover: 'Single' },
  { civilian: 'Playlist', undercover: 'Mixtape' },
  { civilian: 'Micro', undercover: 'Casque Studio' },

  // Marques
  { civilian: 'Nike', undercover: 'Adidas' },
  { civilian: 'Puma', undercover: 'Reebok' },
  { civilian: 'Lacoste', undercover: 'Ralph Lauren' },
  { civilian: 'Gucci', undercover: 'Prada' },
  { civilian: 'Zara', undercover: 'H&M' },
  { civilian: 'Apple', undercover: 'Samsung' },
  { civilian: 'Sony', undercover: 'LG' },
  { civilian: 'Coca Cola', undercover: 'Pepsi' },
  { civilian: 'Mc Donalds', undercover: 'Burger King' },
  { civilian: 'KFC', undercover: 'Subway' },
  { civilian: 'New Balance', undercover: 'Asics' },
  { civilian: 'Converse', undercover: 'Vans' },
  { civilian: 'Under Armour', undercover: 'Decathlon' },
  { civilian: 'Levis', undercover: 'Wrangler' },
  { civilian: 'Calvin Klein', undercover: 'Tommy Hilfiger' },
  { civilian: 'Balenciaga', undercover: 'Givenchy' },
  { civilian: 'Louis Vuitton', undercover: 'Dior' },
  { civilian: 'Rolex', undercover: 'Omega' },
  { civilian: 'Tag Heuer', undercover: 'Breitling' },
  { civilian: 'Apple', undercover: 'Google' },
  { civilian: 'Microsoft', undercover: 'Amazon' },
  { civilian: 'Intel', undercover: 'AMD' },
  { civilian: 'Nvidia', undercover: 'Radeon' },
  { civilian: 'Xiaomi', undercover: 'One Plus' },
  { civilian: 'Huawei', undercover: 'Honor' },
  { civilian: 'Oppo', undercover: 'Vivo' },
  { civilian: 'Play Station', undercover: 'Xbox' },
  { civilian: 'Nintendo', undercover: 'Sega' },
  { civilian: 'EA', undercover: 'Ubisoft' },
  { civilian: 'Rockstar', undercover: 'Bethesda' },
  { civilian: 'Netflix', undercover: 'Disney Plus' },
  { civilian: 'Prime Video', undercover: 'Canal Plus' },
  { civilian: 'Spotify', undercover: 'Apple Music' },
  { civilian: 'Deezer', undercover: 'SoundCloud' },
  { civilian: 'Snapchat', undercover: 'Instagram' },
  { civilian: 'Tik Tok', undercover: 'You Tube' },
  { civilian: 'Discord', undercover: 'Slack' },
  { civilian: 'Whats App', undercover: 'Signal' },
  { civilian: 'Telegram', undercover: 'Messenger' },
  { civilian: 'Renault', undercover: 'Peugeot' },
  { civilian: 'Citroen', undercover: 'Volkswagen' },
  { civilian: 'BMW', undercover: 'Mercedes' },
  { civilian: 'Audi', undercover: 'Volvo' },
  { civilian: 'Toyota', undercover: 'Honda' },
  { civilian: 'Nissan', undercover: 'Mazda' },
  { civilian: 'Hyundai', undercover: 'Kia' },
  { civilian: 'Tesla', undercover: 'Polestar' },
  { civilian: 'Ferrari', undercover: 'Lamborghini' },
  { civilian: 'Porsche', undercover: 'Maserati' },
  { civilian: 'Bugatti', undercover: 'McLaren' },
  { civilian: 'Air France', undercover: 'Lufthansa' },
  { civilian: 'Emirates', undercover: 'Qatar Airways' },
  { civilian: 'Ryanair', undercover: 'EasyJet' },
  { civilian: 'Ikea', undercover: 'Conforama' },
  { civilian: 'Leroy Merlin', undercover: 'Castorama' },
  { civilian: 'Carrefour', undercover: 'Auchan' },
  { civilian: 'Leclerc', undercover: 'Intermarche' },
  { civilian: 'Casino', undercover: 'Monoprix' },
  { civilian: 'Aldi', undercover: 'Lidl' },
  { civilian: 'Zara', undercover: 'Uniqlo' },
  { civilian: 'H&M', undercover: 'C&A' },
  { civilian: 'Shein', undercover: 'Temu' },
  { civilian: 'Sephora', undercover: 'Marionnaud' },
  { civilian: 'Nivea', undercover: 'L Oreal' },
  { civilian: 'Maybelline', undercover: 'Revlon' },
  { civilian: 'Coca Cola', undercover: 'Fanta' },
  { civilian: 'Sprite', undercover: '7 Up' },
  { civilian: 'Red Bull', undercover: 'Monster' },
  { civilian: 'Evian', undercover: 'Volvic' },
  { civilian: 'San Pellegrino', undercover: 'Perrier' },
  { civilian: 'Danone', undercover: 'Nestle' },
  { civilian: 'Milka', undercover: 'Lindt' },
  { civilian: 'Kinder', undercover: 'Haribo' },
  { civilian: 'Oreo', undercover: 'LU' },
  { civilian: 'Nutella', undercover: 'Nocciolata' },
  { civilian: 'Mc Donalds', undercover: 'Quick' },
  { civilian: 'Burger King', undercover: 'Five Guys' },
  { civilian: 'Dominos', undercover: 'Pizza Hut' },
  { civilian: 'Starbucks', undercover: 'Costa Coffee' },
  { civilian: 'Nespresso', undercover: 'Senseo' },
  { civilian: 'Samsung', undercover: 'Sony' },
  { civilian: 'Bose', undercover: 'JBL' },
  { civilian: 'Sennheiser', undercover: 'Audio Technica' },

  // Réseaux sociaux
  { civilian: 'Instagram', undercover: 'Tik Tok' },
  { civilian: 'Snapchat', undercover: 'Be Real' },
  { civilian: 'Facebook', undercover: 'X' },
  { civilian: 'You Tube', undercover: 'Twitch' },
  { civilian: 'Whats App', undercover: 'Telegram' },
  { civilian: 'Discord', undercover: 'Messenger' },
  { civilian: 'Linked In', undercover: 'Viadeo' },
  { civilian: 'Reddit', undercover: 'Quora' },

  // Series (titres)
  { civilian: 'Breaking Bad (Série)', undercover: 'Better Call Saul (Série)' },
  { civilian: 'Game Of Thrones (Série)', undercover: 'House Of The Dragon (Série)' },
  { civilian: 'Stranger Things (Série)', undercover: 'Dark (Série)' },
  { civilian: 'The Walking Dead (Série)', undercover: 'Fear The Walking Dead (Série)' },
  { civilian: 'Prison Break (Série)', undercover: 'Oz (Série)' },
  { civilian: 'La Casa De Papel (Série)', undercover: 'Berlin (Série)' },
  { civilian: 'Narcos (Série)', undercover: 'El Chapo (Série)' },
  { civilian: 'Peaky Blinders (Série)', undercover: 'Boardwalk Empire (Série)' },
  { civilian: 'Vikings (Série)', undercover: 'The Last Kingdom (Série)' },
  { civilian: 'The Boys (Série)', undercover: 'Invincible (Série)' },
  { civilian: 'Wednesday (Série)', undercover: 'Riverdale (Série)' },
  { civilian: 'Euphoria (Série)', undercover: 'Skins (Série)' },
  { civilian: 'The Witcher (Série)', undercover: 'Shadow And Bone (Série)' },
  { civilian: 'The Mandalorian (Série)', undercover: 'Ahsoka (Série)' },
  { civilian: 'Loki (Série)', undercover: 'WandaVision (Série)' },
  { civilian: 'The Office (Série)', undercover: 'Parks And Recreation (Série)' },
  { civilian: 'Friends (Série)', undercover: 'How I Met Your Mother (Série)' },
  { civilian: 'Brooklyn Nine Nine (Série)', undercover: 'New Girl (Série)' },
  { civilian: 'Sherlock (Série)', undercover: 'Elementary (Série)' },
  { civilian: 'True Detective (Série)', undercover: 'Mindhunter (Série)' },
  { civilian: 'Dexter (Série)', undercover: 'Hannibal (Série)' },
  { civilian: 'Mr Robot (Série)', undercover: 'Black Mirror (Série)' },
  { civilian: 'The 100 (Série)', undercover: 'Lost (Série)' },
  { civilian: 'Lucifer (Série)', undercover: 'Supernatural (Série)' },
  { civilian: 'Suits (Série)', undercover: 'The Good Wife (Série)' },

  // Series (personnages)
  { civilian: 'Michael Scofield (Perso Série)', undercover: 'Lincoln Burrows (Perso Série)' },
  { civilian: 'Thomas Shelby (Perso Série)', undercover: 'Arthur Shelby (Perso Série)' },
  { civilian: 'Ragnar (Perso Série)', undercover: 'Bjorn (Perso Série)' },
  { civilian: 'Uhtred (Perso Série)', undercover: 'Alfred (Perso Série)' },
  { civilian: 'Eleven (Perso Série)', undercover: 'Max (Perso Série)' },
  { civilian: 'Dustin (Perso Série)', undercover: 'Steve (Perso Série)' },
  { civilian: 'Mike Ross (Perso Série)', undercover: 'Harvey Specter (Perso Série)' },
  { civilian: 'Donna (Perso Série)', undercover: 'Rachel Zane (Perso Série)' },
  { civilian: 'Lucifer (Perso Série)', undercover: 'Chloe (Perso Série)' },
  { civilian: 'Dean Winchester (Perso Série)', undercover: 'Sam Winchester (Perso Série)' },
  { civilian: 'Rick Grimes (Perso Série)', undercover: 'Daryl (Perso Série)' },
  { civilian: 'Negan (Perso Série)', undercover: 'Governor (Perso Série)' },
  { civilian: 'Homelander (Perso Série)', undercover: 'Butcher (Perso Série)' },
  { civilian: 'Frenchie (Perso Série)', undercover: 'Mother S Milk (Perso Série)' },
  { civilian: 'Wednesday (Perso Série)', undercover: 'Enid (Perso Série)' },
  { civilian: 'Joe Goldberg (Perso Série)', undercover: 'Love Quinn (Perso Série)' },
  { civilian: 'Tommy Egan (Perso Série)', undercover: 'Ghost (Perso Série)' },
  { civilian: 'Saul Goodman (Perso Série)', undercover: 'Kim Wexler (Perso Série)' },
  { civilian: 'Omar Little (Perso Série)', undercover: 'Stringer Bell (Perso Série)' },
  { civilian: 'Hank Moody (Perso Série)', undercover: 'Charlie Runkle (Perso Série)' },

  // Appareils tech
  { civilian: 'i Phone (Appareil)', undercover: 'Samsung Galaxy (Appareil)' },
  { civilian: 'i Pad (Appareil)', undercover: 'Tablette Android (Appareil)' },
  { civilian: 'Mac Book (Appareil)', undercover: 'PCPortable (Appareil)' },
  { civilian: 'Air Pods (Appareil)', undercover: 'Galaxy Buds (Appareil)' },
  { civilian: 'Apple Watch (Appareil)', undercover: 'Montre Connectée (Appareil)' },
  { civilian: 'Play Station 5 (Appareil)', undercover: 'Xbox Series (Appareil)' },
  { civilian: 'Nintendo Switch (Appareil)', undercover: 'Steam Deck (Appareil)' },
  { civilian: 'Alexa (Appareil)', undercover: 'Google Home (Appareil)' },
  { civilian: 'Kindle (Appareil)', undercover: 'Kobo (Appareil)' },

  // Insectes et animaux
  { civilian: 'Fourmi', undercover: 'Termite' },
  { civilian: 'Moustique', undercover: 'Mouche' },
  { civilian: 'Coccinelle', undercover: 'Scarabée' },
  { civilian: 'Criquet', undercover: 'Sauterelle' },
  { civilian: 'Araignée', undercover: 'Scorpion' },
  { civilian: 'Chat', undercover: 'Chien' },
  { civilian: 'Tigre', undercover: 'Lion' },
  { civilian: 'Dauphin', undercover: 'Orque' },
  { civilian: 'Panda', undercover: 'Koala' },
  { civilian: 'Loup', undercover: 'Renard' },

  // Boissons
  { civilian: 'Eau', undercover: 'Eau Gazeuse' },
  { civilian: 'Coca', undercover: 'Pepsi' },
  { civilian: 'Fanta', undercover: 'Orangina' },
  { civilian: 'Ice Tea', undercover: 'Arizona' },
  { civilian: 'Café', undercover: 'Expresso' },
  { civilian: 'Thé', undercover: 'Infusion' },
  { civilian: 'Jus Orange', undercover: 'Jus Pomme' },
  { civilian: 'Limonade', undercover: 'Sprite' },
  { civilian: 'Lait', undercover: 'Lait Amande' },
  { civilian: 'Smoothie', undercover: 'Milkshake' },

  // Fruits et fruits exotiques
  { civilian: 'Pomme', undercover: 'Poire' },
  { civilian: 'Fraise', undercover: 'Framboise' },
  { civilian: 'Cerise', undercover: 'Prune' },
  { civilian: 'Raisin', undercover: 'Myrtille' },
  { civilian: 'Banane', undercover: 'Ananas' },
  { civilian: 'Mangue', undercover: 'Papaye' },
  { civilian: 'Fruit De La Passion', undercover: 'Litchi' },
  { civilian: 'Noix De Coco', undercover: 'Kiwi' },
  { civilian: 'Grenade', undercover: 'Figue' },
  { civilian: 'Pastèque', undercover: 'Melon' },

  // Desserts
  { civilian: 'Tiramisu', undercover: 'Panna Cotta' },
  { civilian: 'Mousse Chocolat', undercover: 'Crème Brûlée' },
  { civilian: 'Éclair', undercover: 'Mille Feuille' },
  { civilian: 'Macaron', undercover: 'Cupcake' },
  { civilian: 'Cheesecake', undercover: 'Brownie' },
  { civilian: 'Gaufre', undercover: 'Crêpe' },
  { civilian: 'Glace Vanille', undercover: 'Sorbet Citron' },
  { civilian: 'Donut', undercover: 'Beignet' },
  { civilian: 'Flan', undercover: 'Clafoutis' },
  { civilian: 'Tarte Pomme', undercover: 'Tarte Citron' },

  // Instruments de musique
  { civilian: 'Guitare', undercover: 'Basse' },
  { civilian: 'Piano', undercover: 'Clavier' },
  { civilian: 'Batterie', undercover: 'Cajon' },
  { civilian: 'Violon', undercover: 'Violoncelle' },
  { civilian: 'Saxophone', undercover: 'Trompette' },
  { civilian: 'Flûte', undercover: 'Clarinette' },
  { civilian: 'Ukulélé', undercover: 'Mandoline' },
  { civilian: 'Harpe', undercover: 'Lyre' },
  { civilian: 'Accordéon', undercover: 'Harmonica' },
  { civilian: 'Djembé', undercover: 'Bongo' },

  // Mythologie
  { civilian: 'Zeus (Mythologie)', undercover: 'Poséidon (Mythologie)' },
  { civilian: 'Hadès (Mythologie)', undercover: 'Arès (Mythologie)' },
  { civilian: 'Athéna (Mythologie)', undercover: 'Artémis (Mythologie)' },
  { civilian: 'Hermès (Mythologie)', undercover: 'Apollon (Mythologie)' },
  { civilian: 'Héra (Mythologie)', undercover: 'Déméter (Mythologie)' },
  { civilian: 'Odin (Mythologie)', undercover: 'Thor (Mythologie)' },
  { civilian: 'Loki (Mythologie)', undercover: 'Freya (Mythologie)' },
  { civilian: 'Anubis (Mythologie)', undercover: 'Râ (Mythologie)' },
  { civilian: 'Medusa (Mythologie)', undercover: 'Sphinx (Mythologie)' },
  { civilian: 'Minotaure (Mythologie)', undercover: 'Cyclope (Mythologie)' },

  // Pokémon
  { civilian: 'Pikachu (Pokémon)', undercover: 'Raichu (Pokémon)' },
  { civilian: 'Salamèche (Pokémon)', undercover: 'Reptincel (Pokémon)' },
  { civilian: 'Carapuce (Pokémon)', undercover: 'Carabaffe (Pokémon)' },
  { civilian: 'Bulbizarre (Pokémon)', undercover: 'Herbizarre (Pokémon)' },
  { civilian: 'Evoli (Pokémon)', undercover: 'Aquali (Pokémon)' },
  { civilian: 'Dracaufeu (Pokémon)', undercover: 'Dracolosse (Pokémon)' },
  { civilian: 'Mew (Pokémon)', undercover: 'Mewtwo (Pokémon)' },
  { civilian: 'Rondoudou (Pokémon)', undercover: 'Grodoudou (Pokémon)' },
  { civilian: 'Lucario (Pokémon)', undercover: 'Zoroark (Pokémon)' },
  { civilian: 'Gengar (Pokémon)', undercover: 'Ectoplasma (Pokémon)' },

  // Adulte
  { civilian: 'Missionnaire', undercover: 'Levrette' },
  { civilian: 'Fellation', undercover: 'Cunnilingus' },
  { civilian: 'Préliminaires', undercover: 'Pénétration' },
  { civilian: 'Sexto', undercover: 'Nude' },
  { civilian: 'Lingerie', undercover: 'Nuisette' },
  { civilian: 'Vibromasseur', undercover: 'Godemichet' },
  { civilian: 'Capote', undercover: 'Préservatif' },
  { civilian: 'Libido', undercover: 'Désir' },
  { civilian: 'Domination', undercover: 'Soumission' },
  { civilian: 'Plan cul', undercover: 'Coup d\'un soir' },
  { civilian: '69', undercover: 'Missionnaire' },
  { civilian: 'French kiss', undercover: 'Pelle' },
  { civilian: 'Baiser', undercover: 'Galoche' },
  { civilian: 'Masturbation', undercover: 'Auto plaisir' },
  { civilian: 'Orgasme', undercover: 'Jouissance' },
  { civilian: 'Érection', undercover: 'Excitation' },
  { civilian: 'Gémissement', undercover: 'Soupir' },
  { civilian: 'Strip tease', undercover: 'Lap dance' },
  { civilian: 'Menottes', undercover: 'Bandeau' },
  { civilian: 'Fouet', undercover: 'Paddle' },
  { civilian: 'Bougie', undercover: 'Massage' },
  { civilian: 'Hôtel', undercover: 'Motel' },
  { civilian: 'Jacuzzi', undercover: 'Bain moussant' },
  { civilian: 'Romance', undercover: 'Passion' },
  { civilian: 'Séduction', undercover: 'Drague' },
  { civilian: 'Flirt', undercover: 'Crush' },
  { civilian: 'Fantasme', undercover: 'Kink' },
  { civilian: 'Culotte', undercover: 'String' },
  { civilian: 'Soutien gorge', undercover: 'Body' },
  { civilian: 'Talons', undercover: 'Bas résille' },
  { civilian: 'After', undercover: 'Before' },
  { civilian: 'Spooning', undercover: 'Câlin' },
  { civilian: 'Dirty talk', undercover: 'Talk coquin' },
  { civilian: 'Chambre rouge', undercover: 'Lumière tamisée' },
  { civilian: 'Consentement', undercover: 'Safe word' },

  // Marques de voiture
  { civilian: 'BMW', undercover: 'Audi' },
  { civilian: 'Mercedes', undercover: 'Lexus' },
  { civilian: 'Ferrari', undercover: 'Lamborghini' },
  { civilian: 'Porsche', undercover: 'Maserati' },
  { civilian: 'Bugatti', undercover: 'Koenigsegg' },
  { civilian: 'Tesla', undercover: 'Polestar' },
  { civilian: 'Peugeot', undercover: 'Renault' },
  { civilian: 'Citroen', undercover: 'Fiat' },
  { civilian: 'Toyota', undercover: 'Honda' },
  { civilian: 'Nissan', undercover: 'Mazda' },

  // Mega pack: +500 paires auto-generees
  { civilian: 'Shigaraki (Perso Anime)', undercover: 'Magna (Perso Anime)' },
  { civilian: 'Twice (Perso Anime)', undercover: 'Maki (Perso Anime)' },
  { civilian: 'Panda (Perso Anime)', undercover: 'Tengen Uzui (Perso Anime)' },
  { civilian: 'Satoru (Perso Anime)', undercover: 'Charmy (Perso Anime)' },
  { civilian: 'Nozel (Perso Anime)', undercover: 'Itadori (Perso Anime)' },
  { civilian: 'Choso (Perso Anime)', undercover: 'Nozel (Perso Anime)' },
  { civilian: 'Shoto (Perso Anime)', undercover: 'Gyomei (Perso Anime)' },
  { civilian: 'Dabi (Perso Anime)', undercover: 'Gyomei (Perso Anime)' },
  { civilian: 'Gyomei (Perso Anime)', undercover: 'Endeavor (Perso Anime)' },
  { civilian: 'Aizawa (Perso Anime)', undercover: 'Nanami (Perso Anime)' },
  { civilian: 'Magna (Perso Anime)', undercover: 'Daki (Perso Anime)' },
  { civilian: 'Kanao (Perso Anime)', undercover: 'Todo (Perso Anime)' },
  { civilian: 'Satoru (Perso Anime)', undercover: 'Daki (Perso Anime)' },
  { civilian: 'Giyu (Perso Anime)', undercover: 'Endeavor (Perso Anime)' },
  { civilian: 'Hawks (Perso Anime)', undercover: 'Inumaki (Perso Anime)' },
  { civilian: 'Twice (Perso Anime)', undercover: 'Toga (Perso Anime)' },
  { civilian: 'Charmy (Perso Anime)', undercover: 'Yami (Perso Anime)' },
  { civilian: 'Charmy (Perso Anime)', undercover: 'Inumaki (Perso Anime)' },
  { civilian: 'Daki (Perso Anime)', undercover: 'Shoto (Perso Anime)' },
  { civilian: 'Giyu (Perso Anime)', undercover: 'Yuta (Perso Anime)' },
  { civilian: 'Dabi (Perso Anime)', undercover: 'Charmy (Perso Anime)' },
  { civilian: 'Mirio (Perso Anime)', undercover: 'Sanemi (Perso Anime)' },
  { civilian: 'Mirio (Perso Anime)', undercover: 'Nanami (Perso Anime)' },
  { civilian: 'Hawks (Perso Anime)', undercover: 'Dabi (Perso Anime)' },
  { civilian: 'Wall Sina (Lieu Anime)', undercover: 'Alfheim (Lieu Anime)' },
  { civilian: 'Wano (Lieu Anime)', undercover: 'Kamino (Lieu Anime)' },
  { civilian: 'Impel Down (Lieu Anime)', undercover: 'Kamino (Lieu Anime)' },
  { civilian: 'Water 7 (Lieu Anime)', undercover: 'Wall Maria (Lieu Anime)' },
  { civilian: 'Karakura (Lieu Anime)', undercover: 'Marley (Lieu Anime)' },
  { civilian: 'Impel Down (Lieu Anime)', undercover: 'Las Noches (Lieu Anime)' },
  { civilian: 'Enies Lobby (Lieu Anime)', undercover: 'Marineford (Lieu Anime)' },
  { civilian: 'Wall Maria (Lieu Anime)', undercover: 'Shibuya (Lieu Anime)' },
  { civilian: 'Alfheim (Lieu Anime)', undercover: 'Dressrosa (Lieu Anime)' },
  { civilian: 'Karakura (Lieu Anime)', undercover: 'Skypiea (Lieu Anime)' },
  { civilian: 'Kamino (Lieu Anime)', undercover: 'Soul Society (Lieu Anime)' },
  { civilian: 'Egghead (Lieu Anime)', undercover: 'Dressrosa (Lieu Anime)' },
  { civilian: 'Labyrinthos (Lieu Anime)', undercover: 'Wano (Lieu Anime)' },
  { civilian: 'Aincrad (Lieu Anime)', undercover: 'Alabasta (Lieu Anime)' },
  { civilian: 'Marley (Lieu Anime)', undercover: 'Dressrosa (Lieu Anime)' },
  { civilian: 'Alabasta (Lieu Anime)', undercover: 'Karakura (Lieu Anime)' },
  { civilian: 'Wall Maria (Lieu Anime)', undercover: 'Hueco Mundo (Lieu Anime)' },
  { civilian: 'Shibuya (Lieu Anime)', undercover: 'Aincrad (Lieu Anime)' },
  { civilian: 'Hueco Mundo (Lieu Anime)', undercover: 'Aincrad (Lieu Anime)' },
  { civilian: 'Paradis (Lieu Anime)', undercover: 'Onigashima (Lieu Anime)' },
  { civilian: 'Skypiea (Lieu Anime)', undercover: 'Shibuya (Lieu Anime)' },
  { civilian: 'Kamino (Lieu Anime)', undercover: 'Dressrosa (Lieu Anime)' },
  { civilian: 'Elbaf (Lieu Anime)', undercover: 'Water 7 (Lieu Anime)' },
  { civilian: 'Kamino (Lieu Anime)', undercover: 'Sabaody (Lieu Anime)' },
  { civilian: 'Walter White (Perso Série)', undercover: 'Jesse Pinkman (Perso Série)' },
  { civilian: 'Gus Fring (Perso Série)', undercover: 'Negan (Perso Série)' },
  { civilian: 'Daenerys (Perso Série)', undercover: 'Michonne (Perso Série)' },
  { civilian: 'Sansa Stark (Perso Série)', undercover: 'Sam Winchester (Perso Série)' },
  { civilian: 'Lincoln Burrows (Perso Série)', undercover: 'Jaime (Perso Série)' },
  { civilian: 'Sansa Stark (Perso Série)', undercover: 'Cersei (Perso Série)' },
  { civilian: 'Polly Gray (Perso Série)', undercover: 'Chloe Decker (Perso Série)' },
  { civilian: 'Dean Winchester (Perso Série)', undercover: 'Walter White (Perso Série)' },
  { civilian: 'Saul Goodman (Perso Série)', undercover: 'Jaime (Perso Série)' },
  { civilian: 'Daryl Dixon (Perso Série)', undercover: 'Lincoln Burrows (Perso Série)' },
  { civilian: 'Gus Fring (Perso Série)', undercover: 'Steve Harrington (Perso Série)' },
  { civilian: 'Eleven (Perso Série)', undercover: 'Sam Winchester (Perso Série)' },
  { civilian: 'Arya Stark (Perso Série)', undercover: 'Sherlock Holmes (Perso Série)' },
  { civilian: 'Rick Grimes (Perso Série)', undercover: 'Dean Winchester (Perso Série)' },
  { civilian: 'Eleven (Perso Série)', undercover: 'Cersei (Perso Série)' },
  { civilian: 'Gus Fring (Perso Série)', undercover: 'Dean Winchester (Perso Série)' },
  { civilian: 'Jesse Pinkman (Perso Série)', undercover: 'Saul Goodman (Perso Série)' },
  { civilian: 'Tyrion Lannister (Perso Série)', undercover: 'Michael Scofield (Perso Série)' },
  { civilian: 'Chloe Decker (Perso Série)', undercover: 'Ned Stark (Perso Série)' },
  { civilian: 'Polly Gray (Perso Série)', undercover: 'Sam Winchester (Perso Série)' },
  { civilian: 'Michael Scofield (Perso Série)', undercover: 'Arya Stark (Perso Série)' },
  { civilian: 'Dustin Henderson (Perso Série)', undercover: 'Sherlock Holmes (Perso Série)' },
  { civilian: 'Cersei (Perso Série)', undercover: 'Michael Scofield (Perso Série)' },
  { civilian: 'Sara Tancredi (Perso Série)', undercover: 'Michael Scofield (Perso Série)' },
  { civilian: 'Brooklyn Nine Nine (Série)', undercover: 'House Of The Dragon (Série)' },
  { civilian: 'Better Call Saul (Série)', undercover: 'Euphoria (Série)' },
  { civilian: 'Peaky Blinders (Série)', undercover: 'Breaking Bad (Série)' },
  { civilian: 'The Walking Dead (Série)', undercover: 'Lucifer (Série)' },
  { civilian: 'Prison Break (Série)', undercover: 'Supernatural (Série)' },
  { civilian: 'Friends (Série)', undercover: 'Ozark (Série)' },
  { civilian: 'Narcos (Série)', undercover: 'Wednesday (Série)' },
  { civilian: 'Black Mirror (Série)', undercover: 'True Detective (Série)' },
  { civilian: 'The Last Kingdom (Série)', undercover: 'Prison Break (Série)' },
  { civilian: 'Narcos (Série)', undercover: 'Game Of Thrones (Série)' },
  { civilian: 'Stranger Things (Série)', undercover: 'The 100 (Série)' },
  { civilian: 'The Walking Dead (Série)', undercover: 'Better Call Saul (Série)' },
  { civilian: 'Better Call Saul (Série)', undercover: 'The Last Kingdom (Série)' },
  { civilian: 'Better Call Saul (Série)', undercover: 'Prison Break (Série)' },
  { civilian: 'La Casa De Papel (Série)', undercover: 'Game Of Thrones (Série)' },
  { civilian: 'House Of The Dragon (Série)', undercover: 'Lucifer (Série)' },
  { civilian: 'Brooklyn Nine Nine (Série)', undercover: 'Lucifer (Série)' },
  { civilian: 'The Witcher (Série)', undercover: 'The Boys (Série)' },
  { civilian: 'Peaky Blinders (Série)', undercover: 'The Boys (Série)' },
  { civilian: 'Wednesday (Série)', undercover: 'The Last Kingdom (Série)' },
  { civilian: 'Better Call Saul (Série)', undercover: 'The Office (Série)' },
  { civilian: 'Lucifer (Série)', undercover: 'The Office (Série)' },
  { civilian: 'Mr Robot (Série)', undercover: 'Sherlock (Série)' },
  { civilian: 'The Witcher (Série)', undercover: 'The 100 (Série)' },
  { civilian: 'Alien (Film)', undercover: 'Iron Man (Film)' },
  { civilian: 'Tenet (Film)', undercover: 'Le Parrain (Film)' },
  { civilian: 'Le Parrain (Film)', undercover: 'Le Hobbit (Film)' },
  { civilian: 'Pulp Fiction (Film)', undercover: 'Shutter Island (Film)' },
  { civilian: 'Iron Man (Film)', undercover: 'Batman (Film)' },
  { civilian: 'Je Suis Une Legende (Film)', undercover: 'Godzilla (Film)' },
  { civilian: 'King Kong (Film)', undercover: 'Troie (Film)' },
  { civilian: 'Inception (Film)', undercover: 'Avatar (Film)' },
  { civilian: 'Interstellar (Film)', undercover: 'Predator (Film)' },
  { civilian: 'Iron Man (Film)', undercover: 'Dune (Film)' },
  { civilian: 'Le Seigneur Des Anneaux (Film)', undercover: 'Spider Man (Film)' },
  { civilian: 'Spider Man (Film)', undercover: 'Venom (Film)' },
  { civilian: 'Jurassic Park (Film)', undercover: 'World War Z (Film)' },
  { civilian: 'Avatar (Film)', undercover: 'Godzilla (Film)' },
  { civilian: 'Harry Potter (Film)', undercover: 'Je Suis Une Legende (Film)' },
  { civilian: 'Venom (Film)', undercover: 'Harry Potter (Film)' },
  { civilian: 'Dune (Film)', undercover: 'Mission Impossible (Film)' },
  { civilian: 'Harry Potter (Film)', undercover: 'Matrix (Film)' },
  { civilian: 'Titanic (Film)', undercover: 'Dune (Film)' },
  { civilian: 'Spider Man (Film)', undercover: 'Mission Impossible (Film)' },
  { civilian: 'Le Hobbit (Film)', undercover: 'Matrix (Film)' },
  { civilian: 'Scarface (Film)', undercover: 'Le Parrain (Film)' },
  { civilian: 'King Kong (Film)', undercover: 'James Bond (Film)' },
  { civilian: 'Harry Potter (Film)', undercover: 'Jurassic Park (Film)' },
  { civilian: 'Sauron (Perso Film)', undercover: 'Ron Weasley (Perso Film)' },
  { civilian: 'Sauron (Perso Film)', undercover: 'Morpheus (Perso Film)' },
  { civilian: 'Thor (Perso Film)', undercover: 'Obi Wan (Perso Film)' },
  { civilian: 'Frodon (Perso Film)', undercover: 'Lara Croft (Perso Film)' },
  { civilian: 'Tony Stark (Perso Film)', undercover: 'Gandalf (Perso Film)' },
  { civilian: 'Aragorn (Perso Film)', undercover: 'Gandalf (Perso Film)' },
  { civilian: 'Joker (Perso Film)', undercover: 'John Wick (Perso Film)' },
  { civilian: 'John Wick (Perso Film)', undercover: 'Sam Gamegie (Perso Film)' },
  { civilian: 'Morpheus (Perso Film)', undercover: 'Tony Stark (Perso Film)' },
  { civilian: 'Tony Stark (Perso Film)', undercover: 'Thor (Perso Film)' },
  { civilian: 'Thanos (Perso Film)', undercover: 'Obi Wan (Perso Film)' },
  { civilian: 'Luke Skywalker (Perso Film)', undercover: 'Tony Stark (Perso Film)' },
  { civilian: 'Hermione Granger (Perso Film)', undercover: 'Thor (Perso Film)' },
  { civilian: 'Jack Sparrow (Perso Film)', undercover: 'Voldemort (Perso Film)' },
  { civilian: 'Joker (Perso Film)', undercover: 'Draco Malfoy (Perso Film)' },
  { civilian: 'Harry Potter (Perso Film)', undercover: 'Peter Parker (Perso Film)' },
  { civilian: 'Voldemort (Perso Film)', undercover: 'Legolas (Perso Film)' },
  { civilian: 'Thanos (Perso Film)', undercover: 'Dumbledore (Perso Film)' },
  { civilian: 'Luke Skywalker (Perso Film)', undercover: 'Han Solo (Perso Film)' },
  { civilian: 'Miles Morales (Perso Film)', undercover: 'Luke Skywalker (Perso Film)' },
  { civilian: 'Sauron (Perso Film)', undercover: 'Hermione Granger (Perso Film)' },
  { civilian: 'Indiana Jones (Perso Film)', undercover: 'Morpheus (Perso Film)' },
  { civilian: 'Leia Organa (Perso Film)', undercover: 'Tony Stark (Perso Film)' },
  { civilian: 'Lara Croft (Perso Film)', undercover: 'Jason Bourne (Perso Film)' },
  { civilian: 'Bugs Bunny (Personnage)', undercover: 'Gros Minet (Personnage)' },
  { civilian: 'Tom (Personnage)', undercover: 'Joe Dalton (Personnage)' },
  { civilian: 'Bob L Eponge (Personnage)', undercover: 'Daffy Duck (Personnage)' },
  { civilian: 'Daffy Duck (Personnage)', undercover: 'Sammy (Personnage)' },
  { civilian: 'Pluto (Personnage)', undercover: 'Brian Griffin (Personnage)' },
  { civilian: 'Brian Griffin (Personnage)', undercover: 'Tom (Personnage)' },
  { civilian: 'Mickey (Personnage)', undercover: 'Rick Sanchez (Personnage)' },
  { civilian: 'Sophie (Personnage)', undercover: 'Sammy (Personnage)' },
  { civilian: 'Marge Simpson (Personnage)', undercover: 'Mr Krabs (Personnage)' },
  { civilian: 'Peter Griffin (Personnage)', undercover: 'Stewie Griffin (Personnage)' },
  { civilian: 'Peter Griffin (Personnage)', undercover: 'Homer Simpson (Personnage)' },
  { civilian: 'Carlo (Personnage)', undercover: 'Lisa Simpson (Personnage)' },
  { civilian: 'Lisa Simpson (Personnage)', undercover: 'Gros Minet (Personnage)' },
  { civilian: 'Plankton (Personnage)', undercover: 'Peter Griffin (Personnage)' },
  { civilian: 'Gros Minet (Personnage)', undercover: 'Lucky Luke (Personnage)' },
  { civilian: 'Bob L Eponge (Personnage)', undercover: 'Marge Simpson (Personnage)' },
  { civilian: 'Marge Simpson (Personnage)', undercover: 'Bart Simpson (Personnage)' },
  { civilian: 'Joe Dalton (Personnage)', undercover: 'Inspecteur Gadget (Personnage)' },
  { civilian: 'Sammy (Personnage)', undercover: 'Pluto (Personnage)' },
  { civilian: 'Jerry (Personnage)', undercover: 'Lisa Simpson (Personnage)' },
  { civilian: 'Donald (Personnage)', undercover: 'Lisa Simpson (Personnage)' },
  { civilian: 'Morty Smith (Personnage)', undercover: 'Scooby Doo (Personnage)' },
  { civilian: 'Peter Griffin (Personnage)', undercover: 'Donald (Personnage)' },
  { civilian: 'Plankton (Personnage)', undercover: 'Obelix (Personnage)' },
  { civilian: 'Deezer (Marque)', undercover: 'Monster (Marque)' },
  { civilian: 'Evian (Marque)', undercover: 'Puma (Marque)' },
  { civilian: 'OnePlus (Marque)', undercover: 'Microsoft (Marque)' },
  { civilian: 'Volvic (Marque)', undercover: 'New Balance (Marque)' },
  { civilian: 'Apple (Marque)', undercover: 'Reebok (Marque)' },
  { civilian: 'Sennheiser (Marque)', undercover: 'Nvidia (Marque)' },
  { civilian: 'Nike (Marque)', undercover: 'Sony (Marque)' },
  { civilian: 'Nvidia (Marque)', undercover: 'Netflix (Marque)' },
  { civilian: 'Nike (Marque)', undercover: 'OnePlus (Marque)' },
  { civilian: 'Xiaomi (Marque)', undercover: 'Puma (Marque)' },
  { civilian: 'Google (Marque)', undercover: 'LG (Marque)' },
  { civilian: 'Nike (Marque)', undercover: 'Volvic (Marque)' },
  { civilian: 'Sennheiser (Marque)', undercover: 'Sony (Marque)' },
  { civilian: 'New Balance (Marque)', undercover: 'LG (Marque)' },
  { civilian: 'OnePlus (Marque)', undercover: 'Intel (Marque)' },
  { civilian: 'Deezer (Marque)', undercover: 'Coca Cola (Marque)' },
  { civilian: 'Deezer (Marque)', undercover: 'Reebok (Marque)' },
  { civilian: 'Intel (Marque)', undercover: 'AMD (Marque)' },
  { civilian: 'JBL (Marque)', undercover: 'Milka (Marque)' },
  { civilian: 'Netflix (Marque)', undercover: 'Prime Video (Marque)' },
  { civilian: 'LG (Marque)', undercover: 'Danone (Marque)' },
  { civilian: 'Pepsi (Marque)', undercover: 'AMD (Marque)' },
  { civilian: 'Netflix (Marque)', undercover: 'Monster (Marque)' },
  { civilian: 'Netflix (Marque)', undercover: 'Intel (Marque)' },
  { civilian: 'Poele (Objet)', undercover: 'Parapluie (Objet)' },
  { civilian: 'Cle (Objet)', undercover: 'Casserole (Objet)' },
  { civilian: 'Assiette (Objet)', undercover: 'Telecommande (Objet)' },
  { civilian: 'Bouteille (Objet)', undercover: 'Gourde (Objet)' },
  { civilian: 'Cable USB (Objet)', undercover: 'Ampoule (Objet)' },
  { civilian: 'Casque (Objet)', undercover: 'Cle (Objet)' },
  { civilian: 'Gourde (Objet)', undercover: 'Lampe (Objet)' },
  { civilian: 'Chargeur (Objet)', undercover: 'Souris (Objet)' },
  { civilian: 'Sac a dos (Objet)', undercover: 'Rouleau (Objet)' },
  { civilian: 'Verre (Objet)', undercover: 'Assiette (Objet)' },
  { civilian: 'Montre (Objet)', undercover: 'Cuillere (Objet)' },
  { civilian: 'Sac a dos (Objet)', undercover: 'Cle (Objet)' },
  { civilian: 'Couteau (Objet)', undercover: 'Casque (Objet)' },
  { civilian: 'Casque (Objet)', undercover: 'Gourde (Objet)' },
  { civilian: 'Agenda (Objet)', undercover: 'Souris (Objet)' },
  { civilian: 'Montre (Objet)', undercover: 'Rouleau (Objet)' },
  { civilian: 'Fourchette (Objet)', undercover: 'Parapluie (Objet)' },
  { civilian: 'Casque (Objet)', undercover: 'Pinceau (Objet)' },
  { civilian: 'Poele (Objet)', undercover: 'Ecouteurs (Objet)' },
  { civilian: 'Regle (Objet)', undercover: 'Casserole (Objet)' },
  { civilian: 'Telecommande (Objet)', undercover: 'Valise (Objet)' },
  { civilian: 'Pinceau (Objet)', undercover: 'Parapluie (Objet)' },
  { civilian: 'Montre (Objet)', undercover: 'Lampe (Objet)' },
  { civilian: 'Couteau (Objet)', undercover: 'Valise (Objet)' },
  { civilian: 'Medecin (Métier)', undercover: 'Patissier (Métier)' },
  { civilian: 'Chauffeur (Métier)', undercover: 'Professeur (Métier)' },
  { civilian: 'Instituteur (Métier)', undercover: 'Technicien (Métier)' },
  { civilian: 'Ingenieur (Métier)', undercover: 'Barman (Métier)' },
  { civilian: 'Cascadeur (Métier)', undercover: 'Professeur (Métier)' },
  { civilian: 'Technicien (Métier)', undercover: 'Serveur (Métier)' },
  { civilian: 'Aide soignant (Métier)', undercover: 'Veterinaire (Métier)' },
  { civilian: 'Steward (Métier)', undercover: 'Infirmier (Métier)' },
  { civilian: 'Electricien (Métier)', undercover: 'Avocat (Métier)' },
  { civilian: 'Photographe (Métier)', undercover: 'Boulanger (Métier)' },
  { civilian: 'Cascadeur (Métier)', undercover: 'Boulanger (Métier)' },
  { civilian: 'Cameraman (Métier)', undercover: 'Chauffeur (Métier)' },
  { civilian: 'Professeur (Métier)', undercover: 'Plombier (Métier)' },
  { civilian: 'Chauffeur (Métier)', undercover: 'Journaliste (Métier)' },
  { civilian: 'Infirmier (Métier)', undercover: 'Aide soignant (Métier)' },
  { civilian: 'Journaliste (Métier)', undercover: 'Pilote (Métier)' },
  { civilian: 'Electricien (Métier)', undercover: 'Rappeur (Métier)' },
  { civilian: 'Cascadeur (Métier)', undercover: 'Acteur (Métier)' },
  { civilian: 'Medecin (Métier)', undercover: 'Policier (Métier)' },
  { civilian: 'Livreur (Métier)', undercover: 'Ingenieur (Métier)' },
  { civilian: 'Journaliste (Métier)', undercover: 'Chef (Métier)' },
  { civilian: 'Presentateur (Métier)', undercover: 'Chauffeur (Métier)' },
  { civilian: 'Pilote (Métier)', undercover: 'Barman (Métier)' },
  { civilian: 'Chirurgien (Métier)', undercover: 'Cameraman (Métier)' },
  { civilian: 'Nuggets (Nourriture)', undercover: 'Quiche (Nourriture)' },
  { civilian: 'Pizza (Nourriture)', undercover: 'Saumon (Nourriture)' },
  { civilian: 'Hot Dog (Nourriture)', undercover: 'Tacos (Nourriture)' },
  { civilian: 'Ratatouille (Nourriture)', undercover: 'Paella (Nourriture)' },
  { civilian: 'Steak (Nourriture)', undercover: 'Ratatouille (Nourriture)' },
  { civilian: 'Steak (Nourriture)', undercover: 'Couscous (Nourriture)' },
  { civilian: 'Risotto (Nourriture)', undercover: 'Omelette (Nourriture)' },
  { civilian: 'Saumon (Nourriture)', undercover: 'Sushi (Nourriture)' },
  { civilian: 'Couscous (Nourriture)', undercover: 'Nuggets (Nourriture)' },
  { civilian: 'Dinde (Nourriture)', undercover: 'Steak (Nourriture)' },
  { civilian: 'Potatoes (Nourriture)', undercover: 'Couscous (Nourriture)' },
  { civilian: 'Maki (Nourriture)', undercover: 'Dinde (Nourriture)' },
  { civilian: 'Frites (Nourriture)', undercover: 'Maki (Nourriture)' },
  { civilian: 'Gyoza (Nourriture)', undercover: 'Risotto (Nourriture)' },
  { civilian: 'Poulet (Nourriture)', undercover: 'Ramen (Nourriture)' },
  { civilian: 'Thon (Nourriture)', undercover: 'Sandwich (Nourriture)' },
  { civilian: 'Paella (Nourriture)', undercover: 'Omelette (Nourriture)' },
  { civilian: 'Pates (Nourriture)', undercover: 'Burrito (Nourriture)' },
  { civilian: 'Kebab (Nourriture)', undercover: 'Paella (Nourriture)' },
  { civilian: 'Cheeseburger (Nourriture)', undercover: 'Ramen (Nourriture)' },
  { civilian: 'Tacos (Nourriture)', undercover: 'Maki (Nourriture)' },
  { civilian: 'Cheeseburger (Nourriture)', undercover: 'Riz (Nourriture)' },
  { civilian: 'Pates (Nourriture)', undercover: 'Escalope (Nourriture)' },
  { civilian: 'Omelette (Nourriture)', undercover: 'Lasagne (Nourriture)' },
  { civilian: 'Libellule (Animal)', undercover: 'Faucon (Animal)' },
  { civilian: 'Guepe (Animal)', undercover: 'Lapin (Animal)' },
  { civilian: 'Libellule (Animal)', undercover: 'Orque (Animal)' },
  { civilian: 'Crocodile (Animal)', undercover: 'Mouton (Animal)' },
  { civilian: 'Crocodile (Animal)', undercover: 'Leopard (Animal)' },
  { civilian: 'Papillon (Animal)', undercover: 'Aigle (Animal)' },
  { civilian: 'Serpent (Animal)', undercover: 'Dauphin (Animal)' },
  { civilian: 'Abeille (Animal)', undercover: 'Faucon (Animal)' },
  { civilian: 'Lievre (Animal)', undercover: 'Aigle (Animal)' },
  { civilian: 'Lion (Animal)', undercover: 'Crocodile (Animal)' },
  { civilian: 'Oie (Animal)', undercover: 'Orque (Animal)' },
  { civilian: 'Requin (Animal)', undercover: 'Tortue (Animal)' },
  { civilian: 'Koala (Animal)', undercover: 'Guepe (Animal)' },
  { civilian: 'Cheval (Animal)', undercover: 'Dauphin (Animal)' },
  { civilian: 'Vache (Animal)', undercover: 'Taureau (Animal)' },
  { civilian: 'Panthere (Animal)', undercover: 'Cheval (Animal)' },
  { civilian: 'Abeille (Animal)', undercover: 'Mouton (Animal)' },
  { civilian: 'Dinde (Animal)', undercover: 'Chat (Animal)' },
  { civilian: 'Loup (Animal)', undercover: 'Poule (Animal)' },
  { civilian: 'Taureau (Animal)', undercover: 'Chevre (Animal)' },
  { civilian: 'Lievre (Animal)', undercover: 'Lion (Animal)' },
  { civilian: 'Chien (Animal)', undercover: 'Guepe (Animal)' },
  { civilian: 'Mouton (Animal)', undercover: 'Papillon (Animal)' },
  { civilian: 'Loup (Animal)', undercover: 'Libellule (Animal)' },
  { civilian: 'Musculation (Sport)', undercover: 'Triathlon (Sport)' },
  { civilian: 'Crossfit (Sport)', undercover: 'Athletisme (Sport)' },
  { civilian: 'Athletisme (Sport)', undercover: 'Judo (Sport)' },
  { civilian: 'VTT (Sport)', undercover: 'Escrime (Sport)' },
  { civilian: 'Bodyboard (Sport)', undercover: 'Skate (Sport)' },
  { civilian: 'Volley (Sport)', undercover: 'Petanque (Sport)' },
  { civilian: 'Plongeon (Sport)', undercover: 'Golf (Sport)' },
  { civilian: 'Judo (Sport)', undercover: 'Handball (Sport)' },
  { civilian: 'Musculation (Sport)', undercover: 'Ski (Sport)' },
  { civilian: 'Musculation (Sport)', undercover: 'Crossfit (Sport)' },
  { civilian: 'Pilates (Sport)', undercover: 'Badminton (Sport)' },
  { civilian: 'Golf (Sport)', undercover: 'Escrime (Sport)' },
  { civilian: 'Boxe (Sport)', undercover: 'Skate (Sport)' },
  { civilian: 'Escalade (Sport)', undercover: 'Football (Sport)' },
  { civilian: 'Plongeon (Sport)', undercover: 'Surf (Sport)' },
  { civilian: 'Cyclisme (Sport)', undercover: 'MMA (Sport)' },
  { civilian: 'Basket (Sport)', undercover: 'Tennis (Sport)' },
  { civilian: 'Natation (Sport)', undercover: 'Basket (Sport)' },
  { civilian: 'Taekwondo (Sport)', undercover: 'MMA (Sport)' },
  { civilian: 'Pilates (Sport)', undercover: 'Petanque (Sport)' },
  { civilian: 'Escrime (Sport)', undercover: 'Escalade (Sport)' },
  { civilian: 'Ski (Sport)', undercover: 'Basket (Sport)' },
  { civilian: 'Natation (Sport)', undercover: 'Roller (Sport)' },
  { civilian: 'Bodyboard (Sport)', undercover: 'Volley (Sport)' },
  { civilian: 'Messenger (Tech)', undercover: 'Windows (Tech)' },
  { civilian: 'Reddit (Tech)', undercover: 'TypeScript (Tech)' },
  { civilian: 'Teamspeak (Tech)', undercover: 'JavaScript (Tech)' },
  { civilian: 'WhatsApp (Tech)', undercover: 'Teamspeak (Tech)' },
  { civilian: 'Signal (Tech)', undercover: 'JavaScript (Tech)' },
  { civilian: 'Bluetooth (Tech)', undercover: 'Instagram (Tech)' },
  { civilian: 'Backend (Tech)', undercover: 'NodeJS (Tech)' },
  { civilian: 'Twitch (Tech)', undercover: 'Quora (Tech)' },
  { civilian: 'Signal (Tech)', undercover: '5G (Tech)' },
  { civilian: 'React (Tech)', undercover: 'Discord (Tech)' },
  { civilian: 'WiFi (Tech)', undercover: 'iOS (Tech)' },
  { civilian: 'Teamspeak (Tech)', undercover: 'API (Tech)' },
  { civilian: 'React (Tech)', undercover: 'Snapchat (Tech)' },
  { civilian: 'Teamspeak (Tech)', undercover: 'NFC (Tech)' },
  { civilian: 'Snapchat (Tech)', undercover: 'Linux (Tech)' },
  { civilian: 'Google (Tech)', undercover: 'Vue (Tech)' },
  { civilian: 'Windows (Tech)', undercover: 'Twitch (Tech)' },
  { civilian: 'Bing (Tech)', undercover: 'WhatsApp (Tech)' },
  { civilian: 'Bing (Tech)', undercover: 'Reddit (Tech)' },
  { civilian: 'Frontend (Tech)', undercover: 'Messenger (Tech)' },
  { civilian: 'Messenger (Tech)', undercover: 'Signal (Tech)' },
  { civilian: 'Twitch (Tech)', undercover: 'Messenger (Tech)' },
  { civilian: 'YouTube (Tech)', undercover: 'iOS (Tech)' },
  { civilian: 'Discord (Tech)', undercover: 'Google (Tech)' },
  { civilian: 'The (Boisson)', undercover: 'Capri Sun (Boisson)' },
  { civilian: 'Red Bull (Boisson)', undercover: 'San Pellegrino (Boisson)' },
  { civilian: 'Mojito (Boisson)', undercover: 'Red Bull (Boisson)' },
  { civilian: 'Fanta (Boisson)', undercover: 'Smoothie (Boisson)' },
  { civilian: 'Orangina (Boisson)', undercover: 'Bubble Tea (Boisson)' },
  { civilian: 'Mojito (Boisson)', undercover: 'Sirop grenadine (Boisson)' },
  { civilian: 'Sirop grenadine (Boisson)', undercover: 'Bubble Tea (Boisson)' },
  { civilian: 'Matcha (Boisson)', undercover: 'Mojito (Boisson)' },
  { civilian: 'The (Boisson)', undercover: 'Orangina (Boisson)' },
  { civilian: 'Sirop grenadine (Boisson)', undercover: 'Red Bull (Boisson)' },
  { civilian: 'Lait d amande (Boisson)', undercover: 'Cafe (Boisson)' },
  { civilian: 'Cafe (Boisson)', undercover: 'Infusion (Boisson)' },
  { civilian: 'Infusion (Boisson)', undercover: 'Virgin Mojito (Boisson)' },
  { civilian: 'Jus de pomme (Boisson)', undercover: 'Arizona (Boisson)' },
  { civilian: 'Pepsi (Boisson)', undercover: 'Smoothie (Boisson)' },
  { civilian: 'Eau (Boisson)', undercover: 'Smoothie (Boisson)' },
  { civilian: 'Lait d amande (Boisson)', undercover: 'Limonade (Boisson)' },
  { civilian: 'Virgin Mojito (Boisson)', undercover: 'Expresso (Boisson)' },
  { civilian: 'Chocolat chaud (Boisson)', undercover: 'Coca (Boisson)' },
  { civilian: 'Expresso (Boisson)', undercover: 'Orangina (Boisson)' },
  { civilian: 'Cidre (Boisson)', undercover: 'Infusion (Boisson)' },
  { civilian: 'Eau (Boisson)', undercover: 'Fanta (Boisson)' },
  { civilian: 'Monster (Boisson)', undercover: 'Matcha (Boisson)' },
  { civilian: 'Cafe (Boisson)', undercover: 'San Pellegrino (Boisson)' },
  { civilian: 'Banane (Fruit/Dessert)', undercover: 'Fraise (Fruit/Dessert)' },
  { civilian: 'Mangue (Fruit/Dessert)', undercover: 'Crepe (Fruit/Dessert)' },
  { civilian: 'Macaron (Fruit/Dessert)', undercover: 'Litchi (Fruit/Dessert)' },
  { civilian: 'Noix de coco (Fruit/Dessert)', undercover: 'Fruit de la passion (Fruit/Dessert)' },
  { civilian: 'Pomme (Fruit/Dessert)', undercover: 'Raisin (Fruit/Dessert)' },
  { civilian: 'Mangue (Fruit/Dessert)', undercover: 'Kiwi (Fruit/Dessert)' },
  { civilian: 'Raisin (Fruit/Dessert)', undercover: 'Panna Cotta (Fruit/Dessert)' },
  { civilian: 'Mille feuille (Fruit/Dessert)', undercover: 'Eclair (Fruit/Dessert)' },
  { civilian: 'Litchi (Fruit/Dessert)', undercover: 'Cerise (Fruit/Dessert)' },
  { civilian: 'Banane (Fruit/Dessert)', undercover: 'Mangue (Fruit/Dessert)' },
  { civilian: 'Kiwi (Fruit/Dessert)', undercover: 'Papaye (Fruit/Dessert)' },
  { civilian: 'Framboise (Fruit/Dessert)', undercover: 'Melon (Fruit/Dessert)' },
  { civilian: 'Mangue (Fruit/Dessert)', undercover: 'Ananas (Fruit/Dessert)' },
  { civilian: 'Mangue (Fruit/Dessert)', undercover: 'Pasteque (Fruit/Dessert)' },
  { civilian: 'Pasteque (Fruit/Dessert)', undercover: 'Macaron (Fruit/Dessert)' },
  { civilian: 'Tiramisu (Fruit/Dessert)', undercover: 'Ananas (Fruit/Dessert)' },
  { civilian: 'Poire (Fruit/Dessert)', undercover: 'Pasteque (Fruit/Dessert)' },
  { civilian: 'Framboise (Fruit/Dessert)', undercover: 'Creme brulee (Fruit/Dessert)' },
  { civilian: 'Poire (Fruit/Dessert)', undercover: 'Papaye (Fruit/Dessert)' },
  { civilian: 'Cerise (Fruit/Dessert)', undercover: 'Cupcake (Fruit/Dessert)' },
  { civilian: 'Noix de coco (Fruit/Dessert)', undercover: 'Raisin (Fruit/Dessert)' },
  { civilian: 'Gaufre (Fruit/Dessert)', undercover: 'Crepe (Fruit/Dessert)' },
  { civilian: 'Framboise (Fruit/Dessert)', undercover: 'Beignet (Fruit/Dessert)' },
  { civilian: 'Crepe (Fruit/Dessert)', undercover: 'Raisin (Fruit/Dessert)' },
  { civilian: 'Bangkok (Lieu)', undercover: 'Busan (Lieu)' },
  { civilian: 'Londres (Lieu)', undercover: 'Dubai (Lieu)' },
  { civilian: 'Gymnase (Lieu)', undercover: 'Rome (Lieu)' },
  { civilian: 'Hopital (Lieu)', undercover: 'Busan (Lieu)' },
  { civilian: 'Doha (Lieu)', undercover: 'Theatre (Lieu)' },
  { civilian: 'Musee (Lieu)', undercover: 'Theatre (Lieu)' },
  { civilian: 'Berlin (Lieu)', undercover: 'Tokyo (Lieu)' },
  { civilian: 'Parc (Lieu)', undercover: 'Madrid (Lieu)' },
  { civilian: 'Stade (Lieu)', undercover: 'Universite (Lieu)' },
  { civilian: 'Parc (Lieu)', undercover: 'Osaka (Lieu)' },
  { civilian: 'Montreal (Lieu)', undercover: 'Hopital (Lieu)' },
  { civilian: 'Singapour (Lieu)', undercover: 'Cinema (Lieu)' },
  { civilian: 'Musee (Lieu)', undercover: 'Melbourne (Lieu)' },
  { civilian: 'Jardin (Lieu)', undercover: 'Tokyo (Lieu)' },
  { civilian: 'Gare (Lieu)', undercover: 'Stade (Lieu)' },
  { civilian: 'Paris (Lieu)', undercover: 'Bangkok (Lieu)' },
  { civilian: 'Busan (Lieu)', undercover: 'New York (Lieu)' },
  { civilian: 'Ecole (Lieu)', undercover: 'Parc (Lieu)' },
  { civilian: 'Paris (Lieu)', undercover: 'Bibliotheque (Lieu)' },
  { civilian: 'Musee (Lieu)', undercover: 'Jardin (Lieu)' },
  { civilian: 'Paris (Lieu)', undercover: 'Londres (Lieu)' },
  { civilian: 'Musee (Lieu)', undercover: 'Parc (Lieu)' },
  { civilian: 'Bibliotheque (Lieu)', undercover: 'Gymnase (Lieu)' },
  { civilian: 'Universite (Lieu)', undercover: 'Galerie (Lieu)' },
  { civilian: 'Tambourin (Instrument)', undercover: 'Tuba (Instrument)' },
  { civilian: 'Piano (Instrument)', undercover: 'Flute (Instrument)' },
  { civilian: 'Sitar (Instrument)', undercover: 'Cajon (Instrument)' },
  { civilian: 'Cor (Instrument)', undercover: 'Clarinette (Instrument)' },
  { civilian: 'Mandoline (Instrument)', undercover: 'Violoncelle (Instrument)' },
  { civilian: 'Clarinette (Instrument)', undercover: 'Tuba (Instrument)' },
  { civilian: 'Basse (Instrument)', undercover: 'Harpe (Instrument)' },
  { civilian: 'Synthe (Instrument)', undercover: 'Guitare (Instrument)' },
  { civilian: 'Guitare (Instrument)', undercover: 'Luth (Instrument)' },
  { civilian: 'Violoncelle (Instrument)', undercover: 'Lyre (Instrument)' },
  { civilian: 'Flute (Instrument)', undercover: 'Trompette (Instrument)' },
  { civilian: 'Contrebasse (Instrument)', undercover: 'Synthe (Instrument)' },
  { civilian: 'Oboe (Instrument)', undercover: 'Tuba (Instrument)' },
  { civilian: 'Piano (Instrument)', undercover: 'Harmonica (Instrument)' },
  { civilian: 'Bongo (Instrument)', undercover: 'Tambourin (Instrument)' },
  { civilian: 'Xylophone (Instrument)', undercover: 'Cajon (Instrument)' },
  { civilian: 'Accordeon (Instrument)', undercover: 'Banjo (Instrument)' },
  { civilian: 'Guitare (Instrument)', undercover: 'Bongo (Instrument)' },
  { civilian: 'Violoncelle (Instrument)', undercover: 'Tambourin (Instrument)' },
  { civilian: 'Trompette (Instrument)', undercover: 'Cajon (Instrument)' },
  { civilian: 'Mandoline (Instrument)', undercover: 'Synthe (Instrument)' },
  { civilian: 'Trompette (Instrument)', undercover: 'Tambourin (Instrument)' },
  { civilian: 'Didgeridoo (Instrument)', undercover: 'Clarinette (Instrument)' },
  { civilian: 'Gengar (Pokémon)', undercover: 'Alakazam (Pokémon)' },
  { civilian: 'Grodoudou (Pokémon)', undercover: 'Pyroli (Pokémon)' },
  { civilian: 'Zoroark (Pokémon)', undercover: 'Raichu (Pokémon)' },
  { civilian: 'Mackogneur (Pokémon)', undercover: 'Mew (Pokémon)' },
  { civilian: 'Lucario (Pokémon)', undercover: 'Carabaffe (Pokémon)' },
  { civilian: 'Voltali (Pokémon)', undercover: 'Mackogneur (Pokémon)' },
  { civilian: 'Tortank (Pokémon)', undercover: 'Lucario (Pokémon)' },
  { civilian: 'Noctali (Pokémon)', undercover: 'Gengar (Pokémon)' },
  { civilian: 'Grodoudou (Pokémon)', undercover: 'Drattak (Pokémon)' },
  { civilian: 'Alakazam (Pokémon)', undercover: 'Pikachu (Pokémon)' },
  { civilian: 'Alakazam (Pokémon)', undercover: 'Mackogneur (Pokémon)' },
  { civilian: 'Raichu (Pokémon)', undercover: 'Togepi (Pokémon)' },
  { civilian: 'Mewtwo (Pokémon)', undercover: 'Zoroark (Pokémon)' },
  { civilian: 'Lokhlass (Pokémon)', undercover: 'Alakazam (Pokémon)' },
  { civilian: 'Ectoplasma (Pokémon)', undercover: 'Togepi (Pokémon)' },
  { civilian: 'Herbizarre (Pokémon)', undercover: 'Aquali (Pokémon)' },
  { civilian: 'Ectoplasma (Pokémon)', undercover: 'Gallame (Pokémon)' },
  { civilian: 'Leviator (Pokémon)', undercover: 'Voltali (Pokémon)' },
  { civilian: 'Pyroli (Pokémon)', undercover: 'Dracaufeu (Pokémon)' },
  { civilian: 'Salameche (Pokémon)', undercover: 'Raichu (Pokémon)' },
  { civilian: 'Pikachu (Pokémon)', undercover: 'Herbizarre (Pokémon)' },
  { civilian: 'Zoroark (Pokémon)', undercover: 'Lucario (Pokémon)' },
  { civilian: 'Grodoudou (Pokémon)', undercover: 'Mentali (Pokémon)' },
  { civilian: 'Ra (Mythologie)', undercover: 'Anubis (Mythologie)' },
  { civilian: 'Cyclope (Mythologie)', undercover: 'Hydre (Mythologie)' },
  { civilian: 'Loki (Mythologie)', undercover: 'Hermes (Mythologie)' },
  { civilian: 'Chimere (Mythologie)', undercover: 'Hera (Mythologie)' },
  { civilian: 'Zeus (Mythologie)', undercover: 'Isis (Mythologie)' },
  { civilian: 'Loki (Mythologie)', undercover: 'Ares (Mythologie)' },
  { civilian: 'Hydre (Mythologie)', undercover: 'Poseidon (Mythologie)' },
  { civilian: 'Meduse (Mythologie)', undercover: 'Sphinx (Mythologie)' },
  { civilian: 'Cerbere (Mythologie)', undercover: 'Hephaistos (Mythologie)' },
  { civilian: 'Cyclope (Mythologie)', undercover: 'Demeter (Mythologie)' },
  { civilian: 'Demeter (Mythologie)', undercover: 'Isis (Mythologie)' },
  { civilian: 'Cyclope (Mythologie)', undercover: 'Apollon (Mythologie)' },
  { civilian: 'Aphrodite (Mythologie)', undercover: 'Orphee (Mythologie)' },
  { civilian: 'Freya (Mythologie)', undercover: 'Poseidon (Mythologie)' },
  { civilian: 'Ares (Mythologie)', undercover: 'Artemis (Mythologie)' },
  { civilian: 'Freya (Mythologie)', undercover: 'Odin (Mythologie)' },
  { civilian: 'Osiris (Mythologie)', undercover: 'Odin (Mythologie)' },
  { civilian: 'Aphrodite (Mythologie)', undercover: 'Loki (Mythologie)' },
  { civilian: 'Ra (Mythologie)', undercover: 'Thor (Mythologie)' },
  { civilian: 'Set (Mythologie)', undercover: 'Odin (Mythologie)' },
  { civilian: 'Ulysse (Mythologie)', undercover: 'Hera (Mythologie)' },
  { civilian: 'Athena (Mythologie)', undercover: 'Chimere (Mythologie)' },
  { civilian: 'Anubis (Mythologie)', undercover: 'Hector (Mythologie)' },
  { civilian: 'Ford (Voiture)', undercover: 'Dodge (Voiture)' },
  { civilian: 'Koenigsegg (Voiture)', undercover: 'Volkswagen (Voiture)' },
  { civilian: 'Bugatti (Voiture)', undercover: 'Skoda (Voiture)' },
  { civilian: 'Maserati (Voiture)', undercover: 'Tesla (Voiture)' },
  { civilian: 'Bugatti (Voiture)', undercover: 'Lexus (Voiture)' },
  { civilian: 'BMW (Voiture)', undercover: 'Mazda (Voiture)' },
  { civilian: 'Hyundai (Voiture)', undercover: 'Nissan (Voiture)' },
  { civilian: 'Mini (Voiture)', undercover: 'Kia (Voiture)' },
  { civilian: 'Alfa Romeo (Voiture)', undercover: 'Seat (Voiture)' },
  { civilian: 'Volvo (Voiture)', undercover: 'Tesla (Voiture)' },
  { civilian: 'Land Rover (Voiture)', undercover: 'Jeep (Voiture)' },
  { civilian: 'Fiat (Voiture)', undercover: 'Peugeot (Voiture)' },
  { civilian: 'Fiat (Voiture)', undercover: 'Mazda (Voiture)' },
  { civilian: 'Subaru (Voiture)', undercover: 'BMW (Voiture)' },
  { civilian: 'Audi (Voiture)', undercover: 'Koenigsegg (Voiture)' },
  { civilian: 'Seat (Voiture)', undercover: 'Ferrari (Voiture)' },
  { civilian: 'Jaguar (Voiture)', undercover: 'BMW (Voiture)' },
  { civilian: 'Dodge (Voiture)', undercover: 'Mazda (Voiture)' },
  { civilian: 'Renault (Voiture)', undercover: 'Skoda (Voiture)' },
  { civilian: 'Toyota (Voiture)', undercover: 'Honda (Voiture)' },
  { civilian: 'Subaru (Voiture)', undercover: 'Porsche (Voiture)' },
  { civilian: 'Koenigsegg (Voiture)', undercover: 'Citroen (Voiture)' },
  { civilian: 'Dodge (Voiture)', undercover: 'Jeep (Voiture)' },
];

module.exports = {
  WORD_PAIRS
};


